<div class="texto">
  <img src="<?php echo $this->baseUrl()."/public/images/portal/geral/pinhonet.png"; ?>" style="margin-left:130px;"/> 
  <br />
</div>

<div class="grupoLista">

  <h1 style="text-align:center; padding-top:20px; margin-left:-30px;"> Utilitários </h1>
  <br /><br />
  <div class="listaUtil">
    <p> <a href="http://www.fandopinho.com.br" target="_blank">Site Fã do Pinho - Apoio a Alta Administração</a></p>
  </div>
  
  <div class="listaUtil">
    <p> <a href="http://www.drashirleydecampos.com.br/categorias/9/" target="_blank">Dicas de Quase Tudo - Informações sobre medicina</a></p>
  </div>
  
  <div class="listaUtil">
    <p> <a href="http://translate.google.com.br/" target="_blank">Google Tradutor - Sistema da google para traduzir páginas</a></p>
  </div>
  
  <div class="listaUtil">
    <p> <a href="http://www.editoracedro.com.br/" target="_blank">No Cenáculo - Guia devocional diário</a></p>
  </div>
  
  <!--
  <div class="listaUtil">
    <p> <a href="http://www.fandopinho.com.br" target="_blank">Pinho Indica - As melhores dicas do Pinho</a></p>
  </div>
  -->
  
  <div class="listaUtil">
    <p> <a href="http://www.poplink.com.br/index.html" target="_blank">Poplink - O que você procura?</a></p>
  </div>
  
  <div class="listaUtil">
    <p> <a href="http://www.flip.pt/tabid/294/Default.aspx" target="_blank">Flip - Corretor ortográfico</a></p>
  </div>
  
  <div class="listaUtil">
    <p> <a href="http://get.adobe.com/br/reader/" target="_blank">Adobe Reader - Leitor de Arquivos PDF</a></p>
  </div>
    <br />  <br />
  <h1 style="text-align:center"> Papéis de parede Pinhonline </h1>
  <br /><br />
    <a href="<?php echo $this->baseUrl()."/public/images/portal/artes/PinhonlinePortal.jpg"; ?>" class="artes" target="_blank"> <img src="<?php echo $this->baseUrl()."/public/images/portal/artes/PinhonlinePortalThumb.jpg"; ?>" /></a>
    <a href="<?php echo $this->baseUrl()."/public/images/portal/artes/PinhonlineMundo.jpg"; ?>" class="artes" target="_blank"> <img src="<?php echo $this->baseUrl()."/public/images/portal/artes/PinhonlineMundoThumb.jpg"; ?>" /></a>
    <a href="<?php echo $this->baseUrl()."/public/images/portal/artes/PinhonlineInteratividade.jpg"; ?>" class="artes" target="_blank"> <img src="<?php echo $this->baseUrl()."/public/images/portal/artes/PinhonlineInteratividadeThumb.jpg"; ?>" /></a>
    <a href="<?php echo $this->baseUrl()."/public/images/portal/artes/PinhonlineInovacao.jpg"; ?>" class="artes" target="_blank"> <img src="<?php echo $this->baseUrl()."/public/images/portal/artes/PinhonlineInovacaoThumb.jpg"; ?>" /></a>
    <br style="clear:both;" /><br style="clear:both;" />
  
</div>