<div class="duplo">
  <img src="<?php echo $this->baseUrl()."/public/images/portal/geral/pinhonet.png"; ?>"/> 
  <br /><br /> <br />
  <p>
  Portal que apóia os Clientes 24 Horas, todos os dias, na Qualificação, Atualização e Desenvolvimento de seus Profissionais, visando assegurar a Alta Competitividade de seus Negócios.<br /> <br /> Nossos Clientes podem alimentar seu Banco de Dados com Infinitas Informações exclusivas para seus Funcionários: 
  </p>
</div>

<img src="<?php echo $this->baseUrl()."/public/images/portal/geral/pinhoPortal.png"; ?>" class="fotoPinhonet"/>

<div class="grupoLista">
  
  <div class="lista">
    <p>Informações Técnicas, Administrativas e Humanas</p>
  </div>
  
  <div class="lista">
    <p>Questionários de Nivelamento Profissional</p>
  </div>
  
  <div class="lista">
    <p>Estabelecimento e Acompanhamento de Metas Gerais e Individuais</p>
  </div>
  
  <div class="lista">
    <p>Políticas de Vendas, Cobrança, Compras, Entregas, Logística etc</p>
  </div>
  
  <div class="lista">
    <p>Programas Motivacionais</p>
  </div>
  
  <div class="lista">
    <p>Manuais de Procedimentos e Orientações</p>
  </div>
  
  <div class="lista">
    <p>Avaliações de Desempenho</p>
  </div>
  
  <div class="lista">
    <p>Treinamentos, Manuais e Conteúdos</p>
  </div>
  
  <div class="lista">
    <p>Troca de Experiências e Informações entre os Funcionários</p>
  </div>
  
  <div class="lista">
    <p>Programas de Ambientação do Funcionário à Empresa e/ou Cargo</p>
  </div>
  
  <div class="lista">
    <p>Pesquisas e Sondagens Diversas</p>
  </div>
  
  <div class="lista">
    <p>Notícias e Avisos Urgentes</p>
  </div>
  
  <div class="lista">
    <p>Convites Diversos</p>
  </div>
  
  <div class="lista">
    <p>Cartões de Aniversário, Parabenizações</p>
  </div>
  
  <div class="lista">
    <p>Alimentos Espirituais</p>
  </div>

</div>