<div class="duplo">
  <img src="<?php echo $this->baseUrl()."/public/images/portal/geral/pinhonet.png"; ?>"/> 
  <br /><br /> <br />
  <p>
  Somos uma Consultoria, com décadas de experiência na capacitação, formação e desenvolvimento de profissionais, sediada no Estado do Rio de Janeiro com atuação em diversos Estados Brasileiros. <br /><br />
Temos interesse, disponibilidade e competência para atuar em qualquer região do Brasil, Mercosul e outros Países mediante contratos específicos.

  </p>
</div>

<div class="texto">
  <p>
A amplitude e a importância da lista de empresas atendidas em nossa trajetória atestam a sintonia das ações da PINHO & CONSULTORES com as necessidades das organizações contratantes.
<br />
<br />
Temos como Foco a Gestão de Negócios Competitivos, o Desenvolvimento de Pessoas e a Utilização de Tecnologias de Resultados, através de uma visão empreendedora, com a qual acreditamos assegurar a satisfação dos envolvidos e contribuir para que estes alcancem e mantenham o sucesso.
<br />
<br />
Somos especialistas na gestão dos recursos essenciais a Alta Performance, com o propósito de desenvolver e divulgar conhecimento na área de comercialização de bens e serviços, visando a manutenção da excelência das organizações, pessoas por nós atendidas.
  </p>
</div>

<div class="texto">

 <h1>Missão</h1>
 <p>
 Apoiar fortemente nossos Clientes na obtenção e sustentação de lucros e Alta Performance, através do desenvolvimento de suas habilidades técnicas, administrativas e humanas, bem como na evolução permanente de seus negócios. 
 </p>
</div>



<div class="texto">

 <h1>Visão</h1>
 <p>
  Ser referencial no mercado em que atuamos como desenvolvedores de talentos e geração de negócios de grande prosperidade entre pessoas felizes!!! 
 </p>
</div>

<img src="<?php echo $this->baseUrl()."/public/images/portal/geral/quemsomos.png"; ?>" class="fotoServicos"/>

<div class="grupoLista">
 <h1>Valores</h1>
 <br />
  <div class="lista">
    <p>Temer a Deus</p>
  </div>
  
  <div class="lista">
    <p>Focar nos Clientes, pessoas e no mercado</p>
  </div>
  
  <div class="lista">
    <p>Ter humor</p>
  </div>

  
  <div class="lista">
    <p>Evoluir/inovar permanentemente, ser um eterno aprendiz</p>
  </div>
  
  <div class="lista">
    <p>Promover a felicidade</p>
  </div>
  
  <div class="lista">
    <p>Cumprir com o que foi combinado</p>
  </div>
  
  <div class="lista">
    <p>Amar o que faz com entusiasmo</p>
  </div>
  
  <div class="lista">
    <p>Gerar fãs</p>
  </div>
  
  <div class="lista">
    <p>Gerar resultados sustentáveis</p>
  </div>
  
  <div class="lista">
    <p>Fortalecer redes de bons profissionais, associativismo</p>
  </div>
  
  <div class="lista">
    <p>Ser reconhecido, grato</p>
  </div>
  
  <div class="lista">
    <p>Contribuir na construção de um mundo melhor</p>
  </div>

</div>
