<?php echo $this->teste; ?>
<script>
jQuery(document).ready(function(){jQuery("#formRecuperarSenha").validationEngine(); });

</script>

<img src="<?php echo $this->baseUrl()."/public/images/portal/geral/pinhonet.png"; ?>" style="margin-left:130px;"/> 

<div class="grupoLista" style="padding-top:10px; text-align:center; <?php if(isset($sucesso) && $sucesso==1) echo ';display:none;'; ?>" >
  
  <div class="listaSolucoes">Se você esqueceu o seu nome de usuário ou senha, você pode pedir que lhe seja enviado por email. Ao solicitar a recuperação, instruções sobre como modificar a sua senha lhe serão enviadas, junto com o seu nome de usuário.<br />
<br />
    <form action="recuperarsenha" method="post" name="formRecuperarSenha" id="formRecuperarSenha">
      <table border="0" cellpadding="0" cellspacing="0" style="margin:auto" class="tabela">
        <tr>
          <td style="text-align:center;"><p>DIGITE O SEU EMAIL</p></td>
        </tr>
        <tr>
          <td style="text-align:center;"><input type="text" name="emailRecuperar" id="emailRecuperar" class="validate[required,custom[email]]"/></td>
        </tr>
        <tr>
          <td style="text-align:center;"><button type="submit">Recuperar Senha ou Usuário</button></td>
        </tr>
      </table>
    </form>
  </div>
  
  
</div>

<?php
	if (isset($sucesso) && $sucesso==1 )
	{
		?>
		<script>
			alert('Favor verificar o seu e-mail para receber informações de como proceder!');
			window.location = 'portal';
        </script>
        
      	<?php
	}

?>
