<div class="duplo">
  <img src="<?php echo $this->baseUrl()."/public/images/portal/geral/pinhonet.png"; ?>"/> 
  <br /><br /> <br />
  <p><br /> <br /><br /> <br /><br />
  </p>
</div>

<img src="<?php echo $this->baseUrl()."/public/images/portal/geral/servicos.png"; ?>" class="fotoServicos"/>

<div class="grupoLista">
  <br /><br /><br />
  <div class="lista">
    <p>	Apoio a Alta Administração</p>
  </div>
  
  <div class="lista">
    <p>Revitalização Organizacional</p>
  </div>
  
  <div class="lista">
    <p>Formação de Vendedores de Alta Performance</p>
  </div>

  
  <div class="lista">
    <p>Formação de Times de Alta Performance</p>
  </div>
  
  <div class="lista">
    <p>	Programas de Adaptação ao Cargo</p>
  </div>
  
  <div class="lista">
    <p>Marketing Interno - Endomarketing</p>
  </div>
  
  <div class="lista">
    <p>	Estabelecimento de Procedimentos</p>
  </div>
  
  <div class="lista">
    <p>Estruturação e Manutenção de Unidades de Negócios</p>
  </div>
  
  <div class="lista">
    <p>Redução de Custos</p>
  </div>
  
  <div class="lista">
    <p>Monitoramento da Concorrência</p>
  </div>
  
  <div class="lista">
    <p>Pesquisa de Satisfação e Qualidade dos Produtos e/ou Serviços - Pós Venda</p>
  </div>
  
  <div class="lista">
    <p>Programas Motivacionais</p>
  </div>
  
  <div class="lista">
    <p>Programa ALO/ 7D - Arrumação, Limpeza e Organização em Sete Dimensões</p>
  </div>
  
  <div class="lista">
    <p>Programas de Qualidade e Excelência</p>
  </div>
  
  <div class="lista">
    <p>Formação de Líderes de Alta Performance</p>
  </div>
  
  <div class="lista">
    <p>Ambientação & Integração à Empresa</p>
  </div>
  
  <div class="lista">
    <p>Implementação de Programas de Ginástica Laboral</p>
  </div>
  
  <div class="lista3">
    <p>	Avaliações de Desempenho:</p>
    <p class="linha2">Por Resultadosa</p>
    <p class="linha3">Habilidades Profissionais</p>
  </div>
  
  <div class="lista">
    <p>Implementação de Indicadores de Resultados & Qualidade</p>
  </div>
  
  <div class="lista">
    <p>Comunicação Voltada para Resultados Sustentáveis</p>
  </div>
  
  <div class="lista">
    <p>Otimização das Compras</p>
  </div>
  
  <div class="lista">
    <p>Pesquisas de Opinião</p>
  </div>
  
  <div class="lista">
    <p>Treinamentos em Módulos</p>
  </div>
  
  <div class="lista">
    <p>Palestras Motivacionais</p>
  </div>
  
  <div class="lista">
    <p>Segurança, Medicina e Higiene do Trabalho</p>
  </div>
  
  <div class="lista">
    <p>Avaliações de Potencial</p>
  </div>
  
  <div class="lista">
    <p>Planejamentos Estratégicos - Construindo o Futuro</p>
  </div>
  
  <div class="lista">
    <p>Estruturando Recursos Humanos</p>
  </div>
  
  <div class="lista">
    <p>Organização e Acompanhamento de Eventos</p>
  </div>
  
</div>