<div class="duplo"><br /> <br /><br /> <br />
  <img src="<?php echo $this->baseUrl()."/public/images/portal/geral/pinhonet.png"; ?>"/> 
  <br /><br /> <br />
  <p><br /> <br /><br /> <br /><br /> <br />
  </p>
</div>

<img src="<?php echo $this->baseUrl()."/public/images/portal/geral/solucoes.png"; ?>" class="fotoSolucoes"/>

<div class="grupoLista">
  
  <div class="listaSolucoes">
    <p>	Trabalhamos com cada cliente de Forma Personalizada,
atendendo às suas necessidades específicas. </p>
  </div>
  
  <div class="listaSolucoes">
    <p>	Somos, juntos com a Alta Administração, os principais
responsáveis por gerar Mudanças Fundamentais e
Competitivas no modo como a Empresa opera.
 </p>
  </div>
  
  <div class="listaSolucoes">
    <p>	Apoiamos na escolha dos projetos, com as pessoas
mais adequadas, Treinando-as, Desenvolvendo-as e
Acompanhando-as. 
 </p>
  </div>
  
  <div class="listaSolucoes">
    <p>Buscamos fortalecer o espírito do trabalho em equipe,
o associativismo, gerando maior harmonia, união,
eficiência e conquistando assim uma maior satisfação
dos clientes, além de incentivar as pessoas a uma
busca contínua pelo autodesenvolvimento, bem como
conscientização sobre a importância de cada um para
a empresa.
 </p>
  </div>
  
  <div class="listaSolucoes">
    <p>Oferecemos soluções inteligentes visando a Alta Performance
das pessoas individualmente e das empresas como um todo.
 </p>
  </div>
</div>