<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>PinhoOnline</title>

    <script src="http://code.jquery.com/jquery-latest.js"></script>

    <script type="text/javascript">
    // preloader
    $(window).load(function() { $('#preloader-master').fadeOut(300, function() {$('body').css('overflow','visible');$(this).remove();});});
    </script>

    <script type="text/javascript" src="<?php echo $this->baseUrl()."/public/scripts/default/slide/easing.js"; ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl()."/public/scripts/default/slide/cufon.js"; ?>"></script>

    <link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl()."/public/styles/default/slide/estilo.css"; ?>" />
</head>

<body onload="carrega();">

    <div id="preloader-master">
    <div id="preloader"> 
        <span class="helvetica">carregando...</span>
    </div>
    <div id="preloader-carrega"> 
    </div>
    </div>

    <div id="color"></div>

    <a id="bot" href="<?php echo $this->url(array('module'=>'default', 'controller'=>'slide','action'=>'index'),null,1); ?>" > Rever </a>

    <a id="but2" href="<?php echo $this->url(array('module'=>'portal', 'controller'=>'index','action'=>'index'),null,1); ?>"> Acessar Portal </a>

    <div class="mensagem">
        <div class="Banima0">Portal do conhecimento da Pinho & Consultores</div>
        <div class="Banima1">O Pinhonline foi concebido para ser a "universidade"<br />da sua empresa e dos seus profissionais.</div>
        <div class="Banima2">Reúne o saber essencial, as ferramentas de gestão e<br /> inspiração que asseguram a performance competitiva que<br /> fortalece a saúde da organização.</div>
        <div class="anima0">Este "porta joias digital" nos trás alimentos que<br /> nos enriquecem espiritualmente e nos dão vida.</div>
        <div class="anima1">Desfrute deste portal preparado com muito amor por <br />pessoas dedicadas e muito especiais como você. </div>
        <div class="anima2">Ganhe tempo. Conecte-se agora!</div>
        <div class="anima3"><img src="<?php echo $this->baseUrl()."/public/images/default/slide/logo.png"; ?>" /></div>
    </div>

    <script type="text/javascript" src="<?php echo $this->baseUrl()."/public/scripts/default/slide/config.js"; ?>"></script>

    <img src="<?php echo $this->baseUrl()."/public/images/default/slide/bg.jpg"; ?>" id="bg" />

</body>