<div id="criar_conta" title="Criar uma nova conta.">
  <p class="validateTips">Todos os campos são obrigatórios</p><br>
  Após aprovação, você poderá cadastrar suas ofertas. Você receberá por e-mail um nome de usuário e uma senha após a aprovação.<br>
  
 
  <form>
    <fieldset>
      <label for="name">Nome</label>
      <input type="text" name="nome" id="nome" class="text ui-widget-content ui-corner-all" />
      <label for="email">Email (será o seu usuário)</label>
      <input type="text" name="email" id="email" value="" class="text ui-widget-content ui-corner-all" />
      <label for="text">CPF</label>
      <input type="text" name="cpf" id="cpf" value="" class="text ui-widget-content ui-corner-all" />
      <label for="text">CEP residencial</label>
      <input type="text" name="cep_residencial" id="cep_residencial" value="" class="text ui-widget-content ui-corner-all" />
      <label for="text">Número</label>
      <input type="text" name="numero_residencial" id="numero_residencial" value="" class="text ui-widget-content ui-corner-all" />
      <label for="text">Nome Fantasia da Empresa</label>
      <input type="text" name="nome_fantasia" id="nome_fantasia" value="" class="text ui-widget-content ui-corner-all" />
      <label for="text">Razão Social</label>
      <input type="text" name="razao_social" id="razao_social" value="" class="text ui-widget-content ui-corner-all" />
      <label for="text">CNPJ</label>
      <input type="text" name="cnpj" id="cnpj" value="" class="text ui-widget-content ui-corner-all" />
      <label for="text">CEP da empresa</label>
      <input type="text" name="cep_empresa" id="cep_empresa" value="" class="text ui-widget-content ui-corner-all" />
      <label for="text">Número</label>
      <input type="text" name="numero_empresa" id="numero_empresa" value="" class="text ui-widget-content ui-corner-all" />
      <label for="text">Descreva sua empresa e os tipos de ofertas que pretende lançar, de forma breve.</label>
      <textarea rows="6" name="breve" id="breve" value="" class="text ui-widget-content ui-corner-all" ></textarea>
    </fieldset>
  </form>
</div>
<?php
/***
 * formulario de login
 */
?>
<br><br><br><br><br><br>
<div id="login1" class="navbar-inner">
<form onKeyPress="return submitEnter(this,event)" name="formulario" action="<?php echo $this->url(array('module'=>'sistema', 'controller'=>'index','action'=>'logar'),null,1); ?>" method="post">
    <table bgcolor="#CCCCCC" style="margin-top:20px;" width="260" align="center">
        <th colspan="2" bgcolor="#999999" style="color:#FFF;" align="center">Administração</th>
        
        <tr>
            <td >
                <div class="input-prepend" >
                    <span class="add-on">Usuário</span><input  id="login" name="login" type="text" placeholder="email ou cpf">
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="input-prepend">
                    <span class="add-on">Senha&nbsp;&nbsp;</span><input id="senha" name="senha" type="password" placeholder="senha" >
                </div>
            </td>
        </tr>
        <tr>
            <td colspan="2" align="center"><a href="javascript:;" onclick='$( "#criar_conta" ).dialog( "open" )' class="recupera"><i class="icon-wrench"></i>&nbsp;Criar uma conta?</a></td>
        </tr>
        <tr>
            <td align="center" colspan="2"><input class="btn btn-primary" name="logar" type="button" id="logar" value="Entrar" onclick="loga();" />&nbsp;<input name="" class="btn btn-danger" type="reset" value="Redefinir" /></td>
        </tr>
    </table>	
</form>

</div>


<script>
    $( "#criar_conta" ).dialog({
      autoOpen: false,
      height: 500,
      width: 650,
      modal: true,
      buttons: {
        "Enviar": function() {
            envia();
        },
        Cancel: function() {
          $( this ).dialog( "close" );
        }
      },
      close: function() {
        
      }
    });
</script>

<style>
    
    label, input { display:block; }
    input.text { margin-bottom:12px; width:95%; padding: .4em; }
    fieldset { padding:0; border:0; margin-top:25px; }
    h1 { font-size: 1.2em; margin: .6em 0; }
    div#criar_conta { width: 350px; margin: 20px 0; }
    div#criar_conta table { margin: 1em 0; border-collapse: collapse; width: 100%; }
    div#criar_conta table td, div#criar_conta table th { border: 1px solid #eee; padding: .6em 10px; text-align: left; }
    .ui-dialog .ui-state-error { padding: .3em; }
    .validateTips { border: 1px solid transparent; padding: 0.3em; }
 </style>
 
<div id="ajax" style="visibility: hidden">
</div>
<script>
    url = '<?php echo $this->url(array('module'=>'sistema', 'controller'=>'index','action'=>'logar'),null,1); ?>';
    redirect = '<?php echo $this->url(array('module'=>'sistema', 'controller'=>'logado','action'=>'index'),null,1); ?>';
    redirectEad = '<?php echo $this->url(array('module'=>'ead', 'controller'=>'logado','action'=>'index'),null,1); ?>';
    
    function loga()
    {
        divAguarde(true,'login1');
        email = document.getElementById('login').value;
        senha = document.getElementById('senha').value;
        
        ajax(url+'/login/'+email+'/senha/'+senha, 'ajax');
        
        valida = document.getElementById('ajax').innerHTML;
        
        if(valida == 0)
            showAlert('ERRO', 'Login ou senha incorretos!');
        else
        {
            //Se o login der certo, sera redirecionado para a view "logado", view inical padrao, depois de logado, de TODOS os modulos
            //menos o portal
            if(pathArray[2] == "portal")
                window.location.pathname = redirectEad;
            else
                window.location.pathname = redirect;
        }
        
        divAguarde(false,'login1');
            
    }
    
    function envia(){
        url = '<?php echo $this->url(array('module'=>'sistema', 'controller'=>'index','action'=>'ajaxnovaconta'),null,1); ?>';
        nome = document.getElementById('nome').value;
        email = document.getElementById('email').value;
        cpf = document.getElementById('cpf').value;
        cep_residencial = document.getElementById('cep_residencial').value;
        numero_residencial = document.getElementById('numero_residencial').value;
        nome_fantasia = document.getElementById('nome_fantasia').value;
        razao_social = document.getElementById('razao_social').value;
        cnpj = document.getElementById('cnpj').value;
        cep_empresa = document.getElementById('cep_empresa').value;
        numero_empresa = document.getElementById('numero_empresa').value;
        breve = document.getElementById('breve').value;
        
        ajax(url+'/nome/'+nome+'/email/'+email+'/cpf/'+cpf+'/cep_residencial/'+cep_residencial+'/numero_residencial/'+numero_residencial+'/nome_fantasia/'+nome_fantasia+'/razao_social/'+razao_social+'/cnpj/'+cnpj+'/cep_empresa/'+cep_empresa+'/numero_empresa/'+numero_empresa+'/breve/'+breve, 'ajax');
    }
</script>



