<script>
    function loadScript() {
        var script = document.createElement("script");
        script.type = "text/javascript";
        script.src = "https://maps.googleapis.com/maps/api/js?key=AIzaSyD_rwLMkqxBaTjKAa9h9iVk5lwhioACBvE&sensor=true&region=pt_BR&callback=<?php if(isset($this->android)){ echo 'initialize';}else{ echo "getLocation";}?>";
        document.body.appendChild(script);
        
        <?php
            //chamadas pelo android, viram por post, com as coordenadas dadas pelo GPS do aparelho
            if(isset($this->android))
            {
                echo 'lat = '.$this->lat.';';        
                echo 'lng = '.$this->lng.';';
            }
        ?>
      }

      window.onload = loadScript;
      
</script>

<div id="map_canvas" style="width:100%; height:100%"></div>
<div id="tempMap"></div>
<div id="carregando"></div>
<div id="erro"></div>