<?php if( $this->arrayFuncionario->count() == 0 ){ ?>
    <table>    
        <tr>
            <td colspan="2">Nenhum item encontrado</td>
        </tr>
    </table>
<?php }else{ ?>

<table align="center" cellspacing="1">
    <th class="barra_titulo">id</th>
    <th class="barra_titulo">Nome</th>
    
    <?php
    //print_r($this->arrayEmpresa);
    
    if($this->selecionar)
        echo '<th class="barra_titulo">Selecione</th>';
    if($this->editar)
        echo '<th class="barra_titulo">Editar</th>';
    if($this->deletar)
        echo '<th class="barra_titulo">Deletar</th>';
    if($this->liberar)
        echo '<th class="barra_titulo">Liberar</th>';

    foreach ($this->arrayFuncionario as $funcionario): ?>
            <tr class="t_acende">
                <td align="center"><?php echo $funcionario['id_funcionario']; ?></td>
                <td align="center"><?php echo $funcionario['nome']; ?></td>
            
                <?php
                    if($this->selecionar)
                    {    
                        //setId() e removeId() estao em public\scripts\utilitario.js
                        ?>
                        <td align="center" width="16%"><input type="checkbox" name="idFuncionarioTmp[]" id="idFuncionarioTmp" onclick="setId(this.value,'Funcionario');removeId(this.value,'Funcionario',this.id);" value="<?php echo $funcionario['id_funcionario']; ?>"/></td>
                        <?php
                    }
                ?>
                
                <?php
                    if($this->editar)
                    {    
                        ?>
                        <td align="center" width="16%">
                            <a class="btn" href="#"><i class="icon-pencil"></i></a>
                        </td>
                        <?php
                    }
                ?>
                        
                <?php
                    if($this->deletar)
                    {    
                        ?>
                        <td align="center" width="16%">
                            <a class="btn" href="#"><i class="icon-trash"></i></a>
                        </td>
                        <?php
                    }
                ?>
                        
                <?php
                    if($this->liberar)
                    {    
                        ?>
                        <td align="center" width="16%">
                            <a class="btn" href="#"><i class="icon-ok-sign"></i></a>
                        </td>
                        <?php
                    }
                ?>
            </tr>
        <?php endforeach; ?>

</table>
<?php 
    echo $this->paginationControl(
                $this->arrayFuncionario,
                'Sliding',
                'paginator.phtml'
        );
?>
<script>
    remarcaId('Funcionario','idFuncionarioTmp');
</script>    

<?php } //if inicial?>