<?php if( $this->arrayUtilitario->count() == 0 ){ ?>
    <table>    
        <tr>
            <td colspan="2">Nenhum item encontrado</td>
        </tr>
    </table>
<?php }else{ ?>

<table align="center" cellspacing="1">
    <th class="barra_titulo">id</th>
    <th class="barra_titulo">Título</th>
    
    <?php
    //print_r($this->arrayUtilitario);
    
    if($this->editar)
        echo '<th class="barra_titulo">Editar</th>';
    if($this->deletar)
        echo '<th class="barra_titulo">Apagar</th>';
    
    $cont =0;
    
    foreach ($this->arrayUtilitario as $utilitario): ?>
            <tr class="t_acende">
                <td align="center"><?php echo $utilitario['id_'.$this->tabela]; ?></td>
                <td align="center"><?php echo $utilitario['titulo']; ?></td>
            
                <?php
                                    
                    if($this->editar)
                    {    
                        ?>
                        <td align="center" width="16%">
                            <a class="btn" href="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'logado', 'action' => 'editarutilitario','idUtilitario'=>$this->idUtilitario,'idTabela'=>$utilitario['id_'.$this->tabela],'titulo'=>$utilitario['titulo']), null, 1); ?>" ><i class="icon-pencil"></i></a>
                        </td>
                        <?php
                    }
                
                    if($this->deletar)
                    {    
                        ?>
                        <td align="center" width="16%">
                            <a class="btn" href="javascript:;" onclick="showAlertConfirm('Deletar','Tem certeza que deseja excluir este <?php echo $this->tabela;?>?','deletar',[ '<?php echo $utilitario['id_'.$this->tabela];?>']);"><i class="icon-trash"></i></a>
                        </td>
                        <?php
                    }
                
                    
                ?>
                        
            </tr>
        <?php endforeach; ?>

        
        
</table>
<?php 
    echo $this->paginationControl(
                    $this->arrayUtilitario,
                    'Sliding',
                    'paginator.phtml'
            );
?>


<?php } //if inicial?>