<?php if( $this->arrayTime->count() == 0 ){ ?>
    <table>    
        <tr>
            <td colspan="2">Nenhum item encontrado</td>
        </tr>
    </table>
<?php }else{ ?>

<table align="center" cellspacing="1">
    <th class="barra_titulo">id</th>
    <th class="barra_titulo">Título</th>
    
    <?php
    //print_r($this->arrayTime);
    
    if($this->selecionar)
        echo '<th class="barra_titulo">Selecione</th>';
    if($this->editar)
        echo '<th class="barra_titulo">Editar</th>';
    if($this->deletar)
        echo '<th class="barra_titulo">Deletar</th>';
    
    $cont =0;
    foreach ($this->arrayTime as $time): ?>
            <tr class="t_acende">
                <td align="center"><?php echo $time['id_time']; ?></td>
                <td align="center"><?php echo $time['titulo']; ?></td>
            
                <?php
                    if($this->selecionar)
                    {    
                        //setId() e removeId() estao em public\scripts\utilitario.js
                        ?>
                        <td align="center" width="16%"><input type="checkbox" name="idTimeTmp[]" id="idTimeTmp" onclick="setId(this.value,'Time');removeId(this.value,'Time',this.id,<?php echo $cont;?>);setFiltroFuncionario();" value="<?php echo $time['id_time']; ?>"/></td>
                        <?php
                        $cont++;
                    }
                    
                    if($this->editar)
                    {    
                        ?>
                        <td align="center" width="16%">
                            <a class="btn" href="#"><i class="icon-pencil"></i></a>
                        </td>
                        <?php
                    }
                
                    if($this->deletar)
                    {    
                        ?>
                        <td align="center" width="16%">
                            <a class="btn" href="#"><i class="icon-trash"></i></a>
                        </td>
                        <?php
                    }
                ?>
            </tr>
        <?php endforeach; ?>

</table>
<?php 
    echo $this->paginationControl(
                $this->arrayTime,
                'Sliding',
                'paginator.phtml'
        );
?>
<script>
    <?php
        if($this->selecionar)
        {
    ?>
        remarcaId('Time','idTimeTmp');
    <?php
        }
    ?>    
</script>    

<?php } //if inicial?>