<?php if( $this->arrayTime->count() == 0 ){ ?>
    <table>    
        <tr>
            <td colspan="2">Nenhum item encontrado</td>
        </tr>
    </table>
<?php }else{ ?>

<table align="center" cellspacing="1">
    <th class="barra_titulo">id</th>
    <th class="barra_titulo">Título</th>
    
    <?php
    //print_r($this->arrayTime);
    
    if($this->selecionar)
        echo '<th class="barra_titulo">Selecione</th>';
    if($this->escolher)
        echo '<th class="barra_titulo">Escolha</th>';
    if($this->editar)
        echo '<th class="barra_titulo">Editar</th>';
    if($this->deletar)
        echo '<th class="barra_titulo">Apagar</th>';
    if($this->liberar)
        echo '<th class="barra_titulo">Liberar</th>';
    if(($this->adicionar) && (!$this->remover) )
        echo '<th class="barra_titulo">Adicionar</th>';
    if($this->remover)
        echo '<th class="barra_titulo">Remover</th>';
    
    $cont =0;
    
    foreach ($this->arrayTime as $time): ?>
            <tr class="t_acende">
                <td align="center"><?php echo $time['id_time']; ?></td>
                <td align="center"><?php echo $time['titulo']; ?></td>
            
                <?php
                    if($this->selecionar)
                    {    
                        //setId() e removeId() estao em public\scripts\utilitario.js
                        ?>
                        <td align="center" width="16%"><input type="checkbox" name="idTimeTmp[]" id="idTimeTmp" onclick="setId(this.value,'Time');removeId(this.value,'Time',this.id,<?php echo $cont;?>);setFiltroFuncionario();" value="<?php echo $time['id_time']; ?>"/></td>        
                
                        <?php
                        $cont++;
                    }
                    
                    if($this->escolher)
                    {    
                        //setId() e removeId() estao em public\scripts\utilitario.js
                        ?>
                        <td align="center" width="16%"><input class="idTimeTempe" type="radio" name="idTimeTmp" id="idTimeTmp" value="<?php echo $time['id_time']; ?>" onclick="document.getElementById('arrayIdTempTime').value=',';setId(this.value,'Time');"/>
                            <input type="hidden" id="nometime_<?php echo $time['id_time'];?>" value="<?php echo $time['titulo'];?>"
                        </td>
                        
                        <?php
                        $cont++;
                    }
                
                    if($this->editar)
                    {    
                        ?>
                        <td align="center" width="16%">
                            <a class="btn" href="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'logado', 'action' => 'editartime','idTime'=>$time['id_time'],'nomeTime'=>$time['titulo']), null, 1); ?>" ><i class="icon-pencil"></i></a>
                        </td>
                        <?php
                    }
                
                    if($this->deletar)
                    {    
                        ?>
                        <td align="center" width="16%">
                            <a class="btn" href="javascript:;" onclick="showAlertConfirm('Deletar','Ao excluir este time, você irá apagar não apenas dados do time, mas também irá deixar todos os seus funcionários sem time. <br>Tem certeza que deseja excluir este time?','deletar',[ '<?php echo $time['id_time'];?>']);"><i class="icon-trash"></i></a>
                        </td>
                        <?php
                    }
                
                    if($this->liberar)
                    {    
                        ?>
                        <td align="center" width="16%">
                            <a class="btn" href="#"><i class="icon-ok-sign"></i></a>
                        </td>
                        <?php
                    } 
               
                    if($this->adicionar && (!$this->remover))
                    {    
                        ?>
                        <td align="center" width="16%">
                            <a class="btn" href="javascript:;" onclick="setId('<?php echo $time['id_time']; ?>','TimeEscolhido');setTimesVisiveis(1,'');"><i class="icon-plus"></i></a>
                        </td>
                        <?php
                    }
                
                    if($this->remover)
                    {    
                        ?>
                        <td align="center" width="16%">
                            <a class="btn" href="javascript:;" onclick="removeNaStr('<?php echo $time['id_time']; ?>','arrayIdTempTimeEscolhido');setTimesVisiveis(1,'');"><i class="icon-minus"></i></a>
                        </td>
                        <?php
                    }
                ?>
                        
            </tr>
        <?php endforeach; ?>

        
        
</table>
<?php 
    if(!($this->remover))
    {
        echo $this->paginationControl(
                    $this->arrayTime,
                    'Sliding',
                    'paginator.phtml'
            );
    }
?>
<script>
    <?php
        if($this->selecionar)
        {
    ?>
            remarcaId('Time','idTimeTmp');
    <?php
        }
    ?>        
</script> 

<?php } //if inicial?>