<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
//    print_r($this->parametros);

    
?>
<div id="funcionario_add_1"><a  class="btn" href="javascript:;" onclick=""><i id="teste" class="icon-plus"></i></a><br></div>
<div id="funcionario_add_2"><a  class="btn" href="javascript:;" onclick=""><i class="icon-plus"></i></a><br></div>
<div id="teste">
    
</div>
<script>


function domEventsLinkFir2Function2(e) 
{ 
var s = '',
wantedprops=',target,';

for(p in e)
{
if(wantedprops.indexOf(','+p+',')+1)
    s+=e[p].id;
        //s+=p+': '+e[p]+'<br>';
//s+='\n'+p+': '+((typeof(e[p])=='object')?'The \"A\" element':e[p]);


}

document.getElementById('teste').innerHTML = s; 

}

</script>