<?php if( $this->arrayEmpresa->count() == 0 ){ ?>
    <table>    
        <tr>
            <td colspan="2">Nenhum item encontrado</td>
        </tr>
    </table>
<?php }else{ ?>

<table align="center" cellspacing="1">
    <th class="barra_titulo">id</th>
    <th class="barra_titulo">Razão Social</th>
    <th class="barra_titulo">Nome Fantasia</th>
    <th class="barra_titulo">Apelido</th>
    <th class="barra_titulo">CNPJ</th>
    <th class="barra_titulo">Telefone 1</th>
    <th class="barra_titulo">Telefone 2</th>
    
    <?php
    //print_r($this->arrayEmpresa);
    
    if($this->selecionar)
        echo '<th class="barra_titulo">Selecione</th>';
    if($this->editar)
        echo '<th class="barra_titulo">Editar</th>';
    if($this->deletar)
        echo '<th class="barra_titulo">Deletar</th>';
    if($this->liberar)
        echo '<th class="barra_titulo">Liberar</th>';
    
    $cont =0;
    
    foreach ($this->arrayEmpresa as $empresa): ?>
            <tr class="t_acende">
                <td align="center"><?php echo $empresa['id_empresa']; ?></td>
                <td align="center"><?php echo $empresa['razao_social']; ?></td>
                <td align="center"><?php echo $empresa['nome_fantasia']; ?></td>
                <td align="center"><?php echo $empresa['apelido']; ?></td>
                <td align="center"><?php echo $empresa['cnpj']; ?></td>
                <td align="center"><?php echo $empresa['telefone_1']; ?></td>
                <td align="center"><?php echo $empresa['telefone_2']; ?></td>
            
                <?php
                    if($this->selecionar)
                    {    
                        //setId() e removeId() estao em public\scripts\utilitario.js
                        ?>
                        <td align="center" width="16%"><input type="checkbox" name="idEmpresaTmp[]" id="idEmpresaTmp" onclick="setId(this.value,'Empresa');removeId(this.value,'Empresa',this.id,<?php echo $cont;?>);setFiltroTime();setFiltroFuncionario();document.getElementById('todos').checked=false" value="<?php echo $empresa['id_empresa']; ?>"/></td>
                        <?php
                        $cont++;
                    }
                
                    if($this->editar)
                    {    
                        ?>
                        <td align="center" width="16%">
                            <a class="btn" href="#"><i class="icon-pencil"></i></a>
                        </td>
                        <?php
                    }
                
                    if($this->deletar)
                    {    
                        ?>
                        <td align="center" width="16%">
                            <a class="btn" href="#"><i class="icon-trash"></i></a>
                        </td>
                        <?php
                    }
                
                    if($this->liberar)
                    {    
                        ?>
                        <td align="center" width="16%">
                            <a class="btn" href="#"><i class="icon-ok-sign"></i></a>
                        </td>
                        <?php
                    }
                ?>
            </tr>
        <?php endforeach; ?>

        
        
</table>
<?php 
    echo $this->paginationControl(
                $this->arrayEmpresa,
                'Sliding',
                'paginator.phtml'
        );
?>
<script>
    <?php
        if($this->selecionar)
        {
    ?>
            remarcaId('Empresa','idEmpresaTmp');
    <?php
        }
    ?>        
</script> 

<?php } //if inicial?>