<?php if( !$this->arrayIdFuncionalidade && $this->arrayIdFuncionalidade != "0"){ ?>
    <?php if(count($this->arrayUsuarioGrupo) == 0){ ?>
        <table>    
            <tr>
                <td colspan="2">Nenhum item</td>
            </tr>
        </table>
    <?php }else{ ?>
    
    <table align="center" cellspacing="1">
        <th class="barra_titulo">id</th>
        <th class="barra_titulo">Nome</th>

        <?php
        //print_r($this->arrayEmpresa);

        if($this->selecionar)
            echo '<th class="barra_titulo">Selecione</th>';
        if($this->editar)
            echo '<th class="barra_titulo">Editar</th>';
        if($this->deletar)
            echo '<th class="barra_titulo">Apagar</th>';

        $cont=0;
        foreach ($this->arrayUsuarioGrupo as $usuarioGrupo): ?>
                <tr class="t_acende">
                    <td align="center"><?php echo $usuarioGrupo['id_grupo_de_acesso']; ?></td>
                    <td align="center"><?php echo $usuarioGrupo['nome']; ?></td>

                    <?php
                        if($this->selecionar)
                        {    
                            //setId() e removeId() estao em public\scripts\utilitario.js
                            $check = '';
                            
                            if(isset($this->arrayIdGrupo))
                            {
                                foreach ($this->arrayIdGrupo as $IdGrupo)
                                {
                                    
                                    if($usuarioGrupo['id_grupo_de_acesso']==$IdGrupo['id_grupo_de_acesso'])
                                    {   
                                        $check = 'checked="checked"';
                                        break;
                                    }                                    
                                }                            
                            }                            
                            ?>
                            <input type="hidden" id="arrayIdTempFuncionalidade_<?php echo $usuarioGrupo['id_grupo_de_acesso']; ?>" value=",">        
                            <td align="center" width="16%"><input <?php echo $check;?> class="idGrupoTmp" type="checkbox" name="idGrupoTmp[]" id="idGrupoTmp" onclick="carregaMenuTree();getIdFuncionalidade('<?php echo $usuarioGrupo['id_grupo_de_acesso']; ?>');setFuncioGrupo();ddtreemenu.flatten('treemenu1', 'expand');disableLED();" value="<?php echo $usuarioGrupo['id_grupo_de_acesso']; ?>"/></td>
                            <?php

                        }
                        
                    ?>

                    <?php
                        if($this->editar)
                        {    
                            ?>
                            <td align="center" width="16%">
                            <a class="btn" href="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'logado', 'action' => 'editargrupoacesso','idGrupo'=>$usuarioGrupo['id_grupo_de_acesso'],'nomeGrupo'=>$usuarioGrupo['nome']), null, 1); ?>" ><i class="icon-pencil"></i></a>
                        </td>
                            <?php
                        }
                    ?>

                    <?php
                        if($this->deletar)
                        {    
                            ?>
                            <td align="center" width="16%">
                            <a class="btn" href="javascript:;" onclick="showAlertConfirm('Deletar','Todas as funcionalidades desde grupo serão apagadas.','deletar',[ '<?php echo $usuarioGrupo['id_grupo_de_acesso'];?>']);" ><i class="icon-trash"></i></a>
                        </td>
                            <?php
                        }
                    ?>

                </tr>
            <?php endforeach; ?>

    </table>


    <?php } //if arrayUsuarioGrupo
    
    }
    else
    { 
        if($this->arrayIdFuncionalidade == "0")
            echo '';
        else
            echo $this->arrayIdFuncionalidade;
    }//if arrayIdFuncionalidade 
?>
