<?php if( $this->arrayFuncionario->count() == 0 ){ ?>
    <table>    
        <tr>
            <td colspan="2">Nenhum item</td>
        </tr>
    </table>
<?php }else{ ?>

<table align="center" cellspacing="1" >
    <th class="barra_titulo">id</th>
    <th class="barra_titulo">Nome</th>
    <th class="barra_titulo">Apelido</th>
    <th class="barra_titulo">Nome Fantasia</th>
    <th class="barra_titulo">CPF</th>
    <th class="barra_titulo">Telefone 1</th>
    <th class="barra_titulo">Celular 1</th>
    
    <?php
    //print_r($this->arrayEmpresa);
    
    if($this->selecionar)
        echo '<th class="barra_titulo">Selecione</th>';
    if($this->editar)
        echo '<th class="barra_titulo">Editar</th>';
    if($this->deletar)
        echo '<th class="barra_titulo">Deletar</th>';
    if($this->liberar)
        echo '<th class="barra_titulo">Liberar</th>';
    if(($this->adicionar) && (!$this->remover) )
        echo '<th class="barra_titulo">Adicionar</th>';
    if($this->remover)
        echo '<th class="barra_titulo">Remover</th>';
    
    $cont=0;
    foreach ($this->arrayFuncionario as $funcionario): ?>
            <tr class="t_acende">
                <td align="center" ><div <?php if($this->remover){ echo 'class="id_funcionario"';}?> ><?php echo $funcionario['id_funcionario']; ?></div></td>
                <td align="center" ><div id="nome_funcionario_<?php echo $funcionario['id_funcionario'];?>" <?php if($this->remover){ echo 'class="nome_funcionario"';}?>><?php echo $funcionario['nome']; ?></div></td>
                <td align="center"><?php echo $funcionario['apelido']; ?></td>
                <td align="center"><?php echo $funcionario['nome_fantasia']; ?></td>
                <td align="center"><?php echo $funcionario['cpf']; ?></td>
                <td align="center"><?php echo $funcionario['tel_residencial_1']; ?></td>
                <td align="center"><?php echo $funcionario['celular_1']; ?></td>
            
                <?php
                    if($this->selecionar)
                    {    
                        //setId() e removeId() estao em public\scripts\utilitario.js
                        ?>
                        <td align="center" width="16%"><input type="radio" name="idFuncionarioTmp" id="idFuncionarioTmp" onclick="document.getElementById('arrayIdTempFuncionario').value = ',';setId(this.value,'Funcionario');setFuncioGrupo();" value="<?php echo $funcionario['id_funcionario']; ?>"/></td>
                        <?php
                        
                    }
                    $cont++;
                ?>
                
                <?php
                    if($this->editar)
                    {    
                        ?>
                        <td align="center" width="16%">
                            <a class="btn" href="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'logado', 'action' => 'editarfuncionario','idFuncionario'=>$funcionario['id_funcionario'],'nomeFuncionario'=>$funcionario['nome']), null, 1); ?>" ><i class="icon-pencil"></i></a>
                        </td>
                        <?php
                    }
                ?>
                        
                <?php
                    if($this->deletar)
                    {    
                        ?>
                        <td align="center" width="16%">
                            <a class="btn" href="javascript:;" onclick="showAlertConfirm('Deletar','Ao excluir este funcionário, você irá apagar não apenas dados cadastrais, mas também todos os dados do mesmo. (Resposta do QNP, LDA, estatísticas, etc). <br>Tem certeza que deseja excluir este funcionário?  Lembrando que existe a opção de alterar o STATUS do funcionário para inativo, retirando o acesso deste funcionário ao sistema.','deletar',[ '<?php echo $funcionario['id_funcionario'];?>']);" ><i class="icon-trash"></i></a>
                        </td>
                        <?php
                    }
                ?>
                        
                <?php
                    if($this->liberar)
                    {    
                        ?>
                        <td align="center" width="16%">
                            <a class="btn" href="#"><i class="icon-ok-sign"></i></a>
                        </td>
                        <?php
                    }
                ?>
                        
               <?php
                    if($this->adicionar && (!$this->remover))
                    {    
                        ?>
                        <td align="center" width="16%">
                            <a id="funcionario_add_<?php echo $cont;?>" class="btn" href="javascript:;" onclick="setId('<?php echo $funcionario['id_funcionario']; ?>','FuncionarioEscolhido');setFiltroFuncionario('',1);"><i class="icon-plus"></i></a>
                        </td>
                        <?php
                    }
                ?>
                        
               <?php
                    if($this->remover)
                    {    
                        ?>
                        <td align="center" width="16%">
                            <a class="btn" href="javascript:;" onclick="removeNaStr('<?php echo $funcionario['id_funcionario']; ?>','arrayIdTempFuncionarioEscolhido');setFiltroFuncionario('',1);"><i class="icon-minus"></i></a>
                        </td>
                        <?php
                    }
                ?>
            </tr>
        <?php endforeach; ?>

</table>
<?php 
    if(!($this->remover))
    {
        echo $this->paginationControl(
                    $this->arrayFuncionario,
                    'Sliding',
                    'paginator.phtml'
            );
    }
?>
<script>
    <?php
        if($this->selecionar)
        {
    ?>
            remarcaId('Funcionario','idFuncionarioTmp');
    <?php
        }
    ?>
</script>    

<?php } //if inicial?>