<table >	
    <?php
        if($this->setor)
        {
    ?>
    <tr>
        <td align="left" style="width: 235px">
            Setor / Unidade de Negócios: 
        </td>
        <td align="left">
            <?php
                //costumizar o filtro
                if($this->nomeSetor)
                    $nomeId = $this->nomeSetor;
                else
                    $nomeId = "id_setor";
                
                if(!$this->temEvento)
                    $evento = 'onchange="setFiltroFuncionario();"';
                else
                    $evento = $this->temEvento;
                
            ?>
            <select tabindex="30" name="<?php echo $nomeId;?>" id="<?php echo $nomeId;?>" style="width:370px" <?php echo $evento; ?>>
                <option value="">::.. Selecione um Setor / Unidade de Negócios (TODOS) ..::</option>
                <?php
                foreach ($this->arraySetor as $linha) {
                    ?>
                    <option value="<?php echo $linha['id_setor']; ?>"><?php echo $linha['titulo']; ?></option>
                    <?php
                }
                ?>

            </select>&nbsp;<p id="p_setor" class="radio inline"></p>
        </td>
    </tr>
    <?php
        }
        if($this->cargo)
        {    
    ?>
    <tr>
        <td align="left" style="width: 235px">
            Cargo: 
        </td>
        <td align="left">
            <select tabindex="4" name="id_cargo" id="id_cargo" style="width:370px" onchange="setFiltroFuncionario();">
                <option value="">::.. Selecione um Cargo (TODOS) ..::</option>
                <?php
                foreach ($this->arrayCargo as $linha) {
                    ?>
                    <option value="<?php echo $linha['id_cargo']; ?>" ><?php echo $linha['titulo']; ?></option>
                    <?php
                }
                ?>                            
            </select>&nbsp;<p id="p_cargo" class="radio inline"></p>
        </td>
    </tr>
    <?php
        }
        if($this->tipo)
        {    
    ?>
    <tr>
        <td align="left" style="width: 235px">
            Tipo: 
        </td>
        <td align="left">
            <select tabindex="5" name="id_funcionario_tipo" id="id_funcionario_tipo" style="width:370px" onchange="setFiltroFuncionario();" >
                <option value="">::.. Selecione um Tipo (TODOS) ..::</option>
                <?php
                foreach ($this->arrayFuncionario_tipo as $linha) {
                    ?>
                    <option value="<?php echo $linha['id_funcionario_tipo']; ?>" ><?php echo $linha['titulo']; ?></option>
                    <?php
                }
                ?>                            
            </select>&nbsp;<p id="p_tipo" class="radio inline"></p>
        </td>
    </tr>
    <?php
        }            
    ?>
</table>


