<div id="senha">
    <form name="formulario" action="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'logado', 'action' => 'ajaxalterarsenha'), null, 1); ?>" method="post">
       
        <div class="modal_filtro">
            <h4>Alterar a Senha</h4>
            <div align="center" class="form-actions">
                <input type="password" name="senha" id="senha" value="" placeholder="Digite a nova senha">
            </div>
        </div>  
    
        <div align="center" class="form-actions" id="alterar">
            <input type="button" class="btn btn-success" onclick="valida();" value="Salvar">
        </div>        
    </form>
</div> 

<script>
    
    function valida()
    {
        flag=1
        textoMsgErro = '';

        if(document.getElementById('senha').value == "")
        {
            flag = 0;
            textoMsgErro += 'Preencha o campo senha!<br>';
        }
        
        //Se validou
        if(flag)
        {   
            //grava
            ajaxJQuery('senha');
        }
        else
            showAlert('Atenção.',textoMsgErro);
        
    }    
    
</script> 