<h3>Cadastro de Controle de Acesso</h3>
<hr>
CNPJ: &nbsp;&nbsp;&nbsp;&nbsp;
                        <input value="" tabindex="9" name="cnpj" type="text" id="cnpj" size="20" maxlength="18"  />
                        <input type="button" onclick="filtraCnpj();" value="Filtrar por CNPJ" />
                        &nbsp;&nbsp;&nbsp;<input type="radio" name="todos" id="todos" onclick="setTodos();deselecionaTodos();setAjaxFuncionarios();" checked="checked" /> 
                        <b>Exibir todas as empresas</b>
<div id="ajax_empresa" class="modal_ajax">
    
</div>
                        
<script type="text/javascript">
    
    function setPaginator(pagina,query)
    {  
        url = '<?php echo $this->url(array('module' => 'sistema', 'controller' => 'logado', 'action' => 'ajaxempresa','selecionar'=>TRUE), null, 1); ?>'+'/pagina/'+pagina+query;
        ajax(url,'ajax_empresa');
    }
    
    
    
    url = '<?php echo $this->url(array('module' => 'sistema', 'controller' => 'logado', 'action' => 'ajaxempresa','selecionar'=>TRUE), null, 1); ?>';
    ajax(url,'ajax_empresa');
</script>                       