
<h3>Cadastro de Controle de Acesso</h3>
<hr>
<form name="formulario" action="" method="post">
    CNPJ: &nbsp;&nbsp;&nbsp;&nbsp;
    <input value="" tabindex="9" name="cnpj" type="text" id="cnpj" size="20" maxlength="18" class="input-medium search-query" />
    <input type="button" onclick="filtraCnpj();" value="Filtrar por CNPJ"  />
    &nbsp;&nbsp;&nbsp;<input type="radio" name="todos" id="todos" onclick="setFiltroFuncionario('todos');apagaArrayIdTempTime();setFiltroTime();" checked="checked" /> 
    <b>Exibir todas as empresas</b>
    <br>
    <h5>Selecione uma empresa</h5>
    <div id="ajax_empresa" class="modal_ajax" onmouseover="setTabela('empresa');">    
    </div>
    <br>
    <h5>Selecione um time</h5>
    <div id="ajax_time" class="modal_ajax" onmouseover="setTabela('time');">    
    </div>
    <hr>
    <h4>Escolha os funcionários que receberão acessos</h4>
    
    <div id="div_FiltroFuncionrio" class="modal_filtro"><!-- apos selecioar a empresa, essa div aparece-->
        <table align="center">	
            <tr>
                <td align="left">
                    Setor / Unidade de Negócios: 
                </td>
                <td align="left">
                    <select tabindex="30" name="idSetor" id="idSetor" style="width:370px" onchange="setFiltroFuncionario();">
                        <option value="">::.. Selecione um Setor / Unidade de Negócios (TODOS) ..::</option>
                        <?php

                            foreach ($this->arraySetor as $linha)
                            {	
                        ?>
                                <option value="<?php echo $linha['id_setor'];?>"><?php echo $linha['titulo'];?></option>
                        <?php
                            }
                        ?>

                    </select>
                </td>
            </tr>
            <tr>
                <td align="left">
                    Cargo: 
                </td>
                <td align="left">
                    <select tabindex="4" name="idCargo" id="idCargo" style="width:370px" onchange="setFiltroFuncionario();">
                        <option value="">::.. Selecione um Cargo (TODOS) ..::</option>
                        <?php
                            foreach ($this->arrayCargo as $linha)
                            {	
                        ?>
                                <option value="<?php echo $linha['id_cargo'];?>" ><?php echo $linha['titulo'];?></option>
                        <?php
                            }
                        ?>                            
                    </select>
                </td>
            </tr>
            <tr>
                <td align="left">
                    Tipo: 
                </td>
                <td align="left">
                    <select tabindex="5" name="idFuncionario_tipo" id="idFuncionario_tipo" style="width:370px" onchange="setFiltroFuncionario();" >
                        <option value="">::.. Selecione um Tipo (TODOS) ..::</option>
                        <?php
                            foreach ($this->arrayFuncionario_tipo as $linha)
                            {	
                        ?>
                                <option value="<?php echo $linha['id_funcionario_tipo'];?>" ><?php echo $linha['titulo'];?></option>
                        <?php
                            }
                        ?>                            
                    </select>
                </td>
            </tr>
        </table>
        
        <div id="ajax_funcionario" class="modal_ajax" onmouseover="setTabela('funcionario');">    
        </div>
    </div>
    
    <hr>
    <h4>Funcionários escolhidos</h4>
    
    <div id="ajax_funcionario_adicionados" class="modal_ajax" onmouseover="setTabela('funcionario_adicionados');">
    </div>
    
    <hr>
    <h4>Escolha as Empresas Visiveis</h4>
    
    <div id="ajax_empresas_visiveis" class="modal_ajax" onmouseover="setTabela('empresas_visiveis');">
    </div>
    
    <h4>Empresas Escolhidas</h4>
    
    <div id="ajax_empresas_adicionadas" class="modal_ajax" onmouseover="setTabela('empresas_adicionadas');">
    </div>
    
    <hr>
    <h4>Escolha os Times Visiveis</h4>
    
    <div id="ajax_times_visiveis" class="modal_ajax" onmouseover="setTabela('times_visiveis');">
    </div>
    
    <h4>Times Escolhidos</h4>
    
    <div id="ajax_times_adicionados" class="modal_ajax" onmouseover="setTabela('times_adicionados');">
    </div>
    
    <br>
    
    <div class="modal_filtro">
        <h3>Funcionalidades</h3>
        <hr>
        <strong>Escolha as funcionalidades que serão liberadas para os funcionários escolhidos.<br>
        Você tem a opção te escolher um grupo de funcionalidades ou escolher cada funcionalidade uma a uma.<br>
        Lembrando que, ou você escolhe grupos ou diretamente as funcionalidades.<br></strong>
        <hr>
        <h4>Grupos</h4>
        <div id="ajax_grupo_funcionalidades" class="modal_ajax">
        </div>
        <h4>Funcionalidades</h4>
        <div id="ajax_funcionalidades" class="modal_min_auto_size">
            <?php 
                include("/application/modules/sistema/views/scripts/logado/carregamenutree.phtml");
            ?>
        </div>
    </div>
    
    <!-- campos hidden temporarios -->
    <input type="hidden" name="arrayIdTempEmpresa" id="arrayIdTempEmpresa" value=",">
    <input type="hidden" name="arrayIdTempTime"    id="arrayIdTempTime" value=",">
    <input type="hidden" name="arrayIdTempFuncionario"    id="arrayIdTempFuncionario" value=",">
    <input type="hidden" name="arrayIdTempFuncionarioEscolhido"    id="arrayIdTempFuncionarioEscolhido" value=",">
    <input type="hidden" name="arrayIdTempEmpresaEscolhida"    id="arrayIdTempEmpresaEscolhida" value=",">
    <input type="hidden" name="arrayIdTempTimeEscolhido"    id="arrayIdTempTimeEscolhido" value=",">
</form>

    
<?php 
    //URL de TODOS!!!! os ajax
    //$arrayEmpresaLED = $this->arrayEmpresaLED;
    $urlAjaxEmpresa = array('module' => 'sistema', 'controller' => 'logado', 'action' => 'ajaxempresa','selecionar'=>TRUE);
    //$urlAjaxEmpresa = array_merge($urlAjaxEmpresa,$arrayEmpresaLED);
    
    //$arrayTimeLED = $this->arrayTimeLED;
    $urlAjaxTime = array('module' => 'sistema', 'controller' => 'logado', 'action' => 'ajaxtime','selecionar'=>TRUE);
    //$urlAjaxTime = array_merge($urlAjaxTime,$arrayTimeLED);
    
    //$arrayFuncionarioLED = $this->arrayFuncionarioLED;
    $urlAjaxFuncionario = array('module' => 'sistema', 'controller' => 'logado', 'action' => 'ajaxfuncionario','adicionar'=>TRUE);
    //$urlAjaxFuncionario = array_merge($urlAjaxFuncionario,$arrayFuncionarioLED);
    
    $urlAjaxEmpresaVisiveis = array('module' => 'sistema', 'controller' => 'logado', 'action' => 'ajaxempresa','adicionar'=>TRUE);
    $urlAjaxTimeVisiveis = array('module' => 'sistema', 'controller' => 'logado', 'action' => 'ajaxtime','adicionar'=>TRUE);
?>
<script type="text/javascript">    
    
    function apagaArrayIdTempTime()
    {
        document.getElementById('arrayIdTempTime').value=',';
    }
    
    //carrega o menu tree
    //ddtreemenu.createTree(treeid, enablepersist, opt_persist_in_days (default is 1))
    ddtreemenu.createTree("treemenu1", false);
    
    /******************************************************************************/
    //                               INICIO FILTRO
    /******************************************************************************/
    
    function setFiltroTime()
    {
        listaIdEmpresa = document.getElementById('arrayIdTempEmpresa').value;
        listaIdEmpresa = listaIdEmpresa.substr(1,listaIdEmpresa.length-2); //retira a 1º e a ultima virgula
        
        url = '<?php echo $this->url($urlAjaxTime, null, 1); ?>'+'/listaIdEmpresa/'+listaIdEmpresa;
        ajax(url,'ajax_time');
    }
    
    //todos de todas as empresas
    function setFiltroFuncionario(todos,remover,pagina)
    {
        
        listaIdFuncionarioEscolhido = document.getElementById('arrayIdTempFuncionarioEscolhido').value;
        listaIdFuncionarioEscolhido = listaIdFuncionarioEscolhido.substr(1,listaIdFuncionarioEscolhido.length-2); //retira a 1º e a ultima virgula
        url = '<?php echo $this->url($urlAjaxFuncionario, null, 1); ?>'+
                                                        '/listaIdFuncionarioEscolhido/'+listaIdFuncionarioEscolhido;
        if (typeof(todos) == "undefined" || todos=='')
        {    
            
            listaIdEmpresa = document.getElementById('arrayIdTempEmpresa').value;
            listaIdEmpresa = listaIdEmpresa.substr(1,listaIdEmpresa.length-2); //retira a 1º e a ultima virgula
            listaIdTime = document.getElementById('arrayIdTempTime').value;
            listaIdTime = listaIdTime.substr(1,listaIdTime.length-2); //retira a 1º e a ultima virgula
            
            idCargo = document.getElementById('idCargo').value;
            idSetor = document.getElementById('idSetor').value;
            idFuncionario_tipo  = document.getElementById('idFuncionario_tipo').value;
            
            url += '/listaIdEmpresa/'+listaIdEmpresa+
                                                            '/listaIdTime/'+listaIdTime+    
                                                            '/idCargo/'+idCargo+
                                                            '/idSetor/'+idSetor+
                                                            '/idFuncionario_tipo/'+idFuncionario_tipo;
        }
        else
        {
            url2 = '<?php echo $this->url($urlAjaxEmpresa, null, 1); ?>';
            document.getElementById('arrayIdTempEmpresa').value = ',';
            ajax(url2,'ajax_empresa');
        }
        
        if ((typeof(pagina) != "undefined")  )
            url+='/pagina/'+pagina;
        
        ajax(url,'ajax_funcionario');
        
        if ((typeof(remover) != "undefined")  )
        {   
            url += '/remover/1';
            if(document.getElementById('arrayIdTempFuncionarioEscolhido').value != ',')
                ajax(url,'ajax_funcionario_adicionados');
            else
               document.getElementById('ajax_funcionario_adicionados').innerHTML = 'Nenhum item adcionado.';
        }
    }
    
    function filtraCnpj()
    {   
        cnpj = document.getElementById('cnpj').value;
        url = '<?php echo $this->url($urlAjaxEmpresa, null, 1); ?>'+'/cnpj/'+cnpj;
        ajax(url,'ajax_empresa');
    }
    
    function setEmpresasVisiveis(remover,pagina)
    {
        listaIdEmpresasEscolhidas = document.getElementById('arrayIdTempEmpresaEscolhida').value;
        listaIdEmpresasEscolhidas = listaIdEmpresasEscolhidas.substr(1,listaIdEmpresasEscolhidas.length-2); //retira a 1º e a ultima virgula
        
        url = '<?php echo $this->url($urlAjaxEmpresaVisiveis, null, 1); ?>'+'/pagina/'+pagina+
                                                                    '/listaIdEmpresasEscolhidas/'+listaIdEmpresasEscolhidas;
        ajax(url,'ajax_empresas_visiveis');
        
        if ((typeof(remover) != "undefined")  )
        {   
            url += '/remover/1';
            if(document.getElementById('arrayIdTempEmpresaEscolhida').value != ',')
                ajax(url,'ajax_empresas_adicionadas');
            else
               document.getElementById('ajax_empresas_adicionadas').innerHTML = 'Nenhum item adcionado.';
        }
       
    }
    
    function setTimesVisiveis(remover,pagina)
    {
        listaIdTimesEscolhidos = document.getElementById('arrayIdTempTimeEscolhido').value;
        listaIdTimesEscolhidos = listaIdTimesEscolhidos.substr(1,listaIdTimesEscolhidos.length-2); //retira a 1º e a ultima virgula
        
        url = '<?php echo $this->url($urlAjaxTimeVisiveis, null, 1); ?>'+'/pagina/'+pagina+
                                                                    '/listaIdTimesEscolhidos/'+listaIdTimesEscolhidos;
        ajax(url,'ajax_times_visiveis');
        
        if ((typeof(remover) != "undefined")  )
        {   
            //alert('asd');
            url += '/remover/1';
            if(document.getElementById('arrayIdTempTimeEscolhido').value != ',')
                ajax(url,'ajax_times_adicionados');
            else
               document.getElementById('ajax_times_adicionados').innerHTML = 'Nenhum item adcionado.';
        }
       
    }
    
    /******************************************************************************/
    //                               FIM FILTRO
    /******************************************************************************/
    
    /******************************************************************************/
    //                               INICIO AJAX
    /******************************************************************************/
    tabelas='';
    /***
    * Como existe mais de um paginator na pagina, temos que ter o controle da
    * funcao setPaginator() para que o ajax correto seja carregado.
    * Ao passar o mouse sobre cada DIV, essa variavel eh setada
    */ 
    function setTabela(tabela)
    {
        tabelas = tabela;
    }
    
    //ao clicar nos botoes do paginator, essa funcao eh chamada e um determinado
    // ajax eh excudado
    function setPaginator(pagina,query)
    {  
        if(tabelas=='empresa')
        {    
            url = '<?php echo $this->url($urlAjaxEmpresa, null, 1); ?>'+'/pagina/'+pagina+query;
            ajax(url,'ajax_empresa');
        }
        else if(tabelas=='time')
        {
            url = '<?php echo $this->url($urlAjaxTime, null, 1); ?>'+'/pagina/'+pagina+query;
            ajax(url,'ajax_time');
        }
        else if(tabelas=='funcionario')
        {
            setFiltroFuncionario(null,null,pagina);
        }
        else if(tabelas=='funcionario_adicionados')
        {
            setFiltroFuncionario(null,1,pagina);
        }
        else if(tabelas=='empresas_visiveis')
        {
            setEmpresasVisiveis(1,pagina);
        }    
        else if(tabelas=='times_visiveis')
        {
            setTimesVisiveis(1,pagina);
        }
    }    
    
    url = '<?php echo $this->url($urlAjaxEmpresa, null, 1); ?>';
    ajax(url,'ajax_empresa');
    
    url = '<?php echo $this->url($urlAjaxTime, null, 1); ?>';
    ajax(url,'ajax_time');
    
    url = '<?php echo $this->url($urlAjaxFuncionario, null, 1); ?>';
    ajax(url,'ajax_funcionario');
    
    url = '<?php echo $this->url($urlAjaxEmpresaVisiveis, null, 1); ?>';
    ajax(url,'ajax_empresas_visiveis');
    
    url = '<?php echo $this->url($urlAjaxTimeVisiveis, null, 1); ?>';
    ajax(url,'ajax_times_visiveis');
    
    /******************************************************************************/
    //                               FIM AJAX
    /******************************************************************************/
    
    
    
</script>
