<h3>Cadastro de Controle de Acesso</h3>
<hr>
<div id="tabs" style="width:811px;">  
    <form name="formularioCarregaMenu" action="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'logado', 'action' => 'ajaxgravacontroleacesso'), null, 1); ?>" method="post">
        <ul>
            <li><a href="#tabs-3">Funcionário</a></li>
            <li><a href="#tabs-4">Empresas Visíveis</a></li>
            <li><a href="#tabs-5">Times Visíveis</a></li>
            <li><a href="#tabs-6">Funcionalidades</a></li>
        </ul>
        <div id="tabs-3" class="tab_content">
            <div class="modal_min_auto_size">
                <h4>Filtros:</h4>
                CNPJ: &nbsp;&nbsp;&nbsp;&nbsp;
                <input value="" tabindex="9" name="cnpj" type="text" id="cnpj" size="20" maxlength="18" class="input-medium search-query" />
                <input type="button" onclick="filtraCnpj();" value="Filtrar por CNPJ"  />
                &nbsp;&nbsp;&nbsp;<input type="radio" name="todos" id="todos" onclick="setFiltroFuncionario('todos');apagaArrayIdTempTime();setFiltroTime();" checked="checked" /> 
                <b>Exibir todas as empresas</b>
                <hr>
                <h5>Selecione uma empresa</h5>
                <div id="ajax_empresa" class="modal_ajax" onmouseover="setTabela('empresa');">    
                </div>
                <hr>
                <h5>Selecione um time</h5>
                <div id="ajax_time" class="modal_ajax" onmouseover="setTabela('time');">    
                </div>
            </div>
            <br>
            <h4>Escolha os funcionários que receberão acessos</h4>

            <div id="div_FiltroFuncionrio" class="modal_filtro"><!-- apos selecioar a empresa, essa div aparece-->
                <table align="center">	
                    <tr>
                        <td align="left">
                            Setor / Unidade de Negócios: 
                        </td>
                        <td align="left">
                            <select tabindex="30" name="idSetor" id="idSetor" style="width:370px" onchange="setFiltroFuncionario();">
                                <option value="">::.. Selecione um Setor / Unidade de Negócios (TODOS) ..::</option>
                                <?php

                                    foreach ($this->arraySetor as $linha)
                                    {	
                                ?>
                                        <option value="<?php echo $linha['id_setor'];?>"><?php echo $linha['titulo'];?></option>
                                <?php
                                    }
                                ?>

                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td align="left">
                            Cargo: 
                        </td>
                        <td align="left">
                            <select tabindex="4" name="idCargo" id="idCargo" style="width:370px" onchange="setFiltroFuncionario();">
                                <option value="">::.. Selecione um Cargo (TODOS) ..::</option>
                                <?php
                                    foreach ($this->arrayCargo as $linha)
                                    {	
                                ?>
                                        <option value="<?php echo $linha['id_cargo'];?>" ><?php echo $linha['titulo'];?></option>
                                <?php
                                    }
                                ?>                            
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td align="left">
                            Tipo: 
                        </td>
                        <td align="left">
                            <select tabindex="5" name="idFuncionario_tipo" id="idFuncionario_tipo" style="width:370px" onchange="setFiltroFuncionario();" >
                                <option value="">::.. Selecione um Tipo (TODOS) ..::</option>
                                <?php
                                    foreach ($this->arrayFuncionario_tipo as $linha)
                                    {	
                                ?>
                                        <option value="<?php echo $linha['id_funcionario_tipo'];?>" ><?php echo $linha['titulo'];?></option>
                                <?php
                                    }
                                ?>                            
                            </select>
                        </td>
                    </tr>
                </table>

                <div id="ajax_funcionario" class="modal_ajax" onmouseover="setTabela('funcionario');">    
                </div>
            </div>        

            <hr>
            <h4>Funcionários escolhidos</h4>

            <div id="ajax_funcionario_adicionados" class="modal_ajax" onmouseover="setTabela('funcionario_adicionados');">
            </div>
        </div>        
        <div id="tabs-4" class="tab_content">
            <h4>Escolha as Empresas Visiveis</h4>

            <div id="ajax_empresas_visiveis" class="modal_ajax" onmouseover="setTabela('empresas_visiveis');">
            </div>

            <h4>Empresas Escolhidas</h4>

            <div id="ajax_empresas_adicionadas" class="modal_ajax" onmouseover="setTabela('empresas_adicionadas');">
            </div>

        </div>
        <div id="tabs-5" class="tab_content">
            <h4>Escolha os Times Visiveis</h4>

            <div id="ajax_times_visiveis" class="modal_ajax" onmouseover="setTabela('times_visiveis');">
            </div>

            <h4>Times Escolhidos</h4>

            <div id="ajax_times_adicionados" class="modal_ajax" onmouseover="setTabela('times_adicionados');">
            </div>
        </div>
        <div id="tabs-6" class="tab_content">
            <div class="modal_filtro">
                <h3>Funcionalidades</h3>
                <hr>
                <strong>Escolha as funcionalidades que serão liberadas para os funcionários escolhidos.<br>
                Você tem a opção te escolher um grupo de funcionalidades ou escolher cada funcionalidade uma a uma.<br>
                Lembrando que, ou você escolhe grupos ou diretamente as funcionalidades.<br></strong>
                <hr>
                <h4>Grupos</h4>
                <div id="ajax_grupo" class="modal_ajax">
                </div>
                <h4>Funcionalidades</h4>
                <div id="ajax_funcionalidades" class="modal_min_auto_size">

                </div>
            </div>
        </div>    

        <!-- campos hidden temporarios -->
        <input type="hidden" name="arrayIdTempEmpresa" id="arrayIdTempEmpresa" value=",">
        <input type="hidden" name="arrayIdTempTime"    id="arrayIdTempTime" value=",">
        <input type="hidden" name="arrayIdTempFuncionarioEscolhido"    id="arrayIdTempFuncionarioEscolhido" value=",">
        <input type="hidden" name="arrayIdTempEmpresaEscolhida"    id="arrayIdTempEmpresaEscolhida" value=",">
        <input type="hidden" name="arrayIdTempTimeEscolhido"    id="arrayIdTempTimeEscolhido" value=",">
        <div id="ajax_id_funcionalidade" style="display: none"></div>
    
    </div>
    <div align="center" class="form-actions">
        <input type="button" class="btn btn-success" onclick="valida();" value="Gravar">
    </div>
        
    </form>
    
</div>

<script type="text/javascript">      
    
    function valida()
    {
        flag=1
        textoMsgErro = '';

        if(document.getElementById('arrayIdTempFuncionarioEscolhido').value == ",")
        {
            flag = 0;
            textoMsgErro += 'Não há Funcionários escolhidos!<br>';
        }

        if(document.getElementById('arrayIdTempTimeEscolhido').value == ",")
        {
            flag = 0;
            textoMsgErro += 'Não há Times Visiveis escolhidos!<br>';
        }

        if(document.getElementById('arrayIdTempEmpresaEscolhida').value == ",")
        {
            flag = 0;
            textoMsgErro += 'Não há Empresas Visiveis escolhidas!<br>';
        }

        
        //se o funcionario tiver ao menos um grupo de acesso
        if ($('#idGrupoTmp')[0])
        {    
            
            flag1=0;
            flag2=0;
            
            //verifica se ele escolheu algum grupo
            temps = document.forms[0].getElementsByClassName('idGrupoTmp');
            if(temps.length)
            { 
                for (j = 0; j < temps.length; j++)
                {   //alert(temp.length);
                    if(temps[j].checked)
                        flag1=1;
                }
            }
            
            //Ou se ele escolhe funcionalidades
            temps = document.forms[0].getElementsByClassName('idFuncionalidade');
            if(temps.length)
            { 
                for (j = 0; j < temps.length; j++)
                {   //alert(temp.length);
                    if(temps[j].checked)
                        flag2=1;
                }
            }
                        
            if(flag1==0 && flag2==0)
            {
                flag = 0;
                textoMsgErro += 'Não há Funcionalidades escolhidas!<br>';
            }
        }
        else //para o caso do usario não ter nenhum grupo de acesso, verifica apenas as funcionalidades
        {
            flag1=0;
            temps = document.forms[0].getElementsByClassName('idFuncionalidade');
            if(temps.length)
            { 
                for (j = 0; j < temps.length; j++)
                {   //alert(temp.length);
                    if(temps[j].checked)
                        flag1 = 1;
                }
            }
            if(flag1==0)
            {
                flag = 0;
                textoMsgErro += 'Não há Funcionalidade escolhida!<br>';
            }            
        }
        
        //Se validou
        if(flag)
        {            
            temps = document.forms[0].getElementsByClassName('idFuncionalidade');
            desmarcaPai();

            if(temps.length)
            { 
                for (j = 0; j < temps.length; j++)
                {   //alert(temp.length);
                    if(temps[j].checked)
                        marcaPai(temps[j].value);
                }
            }
            
            //grava
            ajaxJQuery('tabs');
        }
        else
            showAlert('Atenção',textoMsgErro);

    }    
    
    //ao clicar nos botoes do paginator, essa funcao eh chamada e um determinado
    // ajax eh excudado
    function setPaginator(pagina,query)
    {  
        //tabelas é setado ao passar o mouse sobre a DIV
        
        if(tabelas=='empresa')
        {    
            url = urlAjaxEmpresa+'/selecionar/1/pagina/'+pagina+query;
            ajax(url,'ajax_empresa');
        }
        else if(tabelas=='time')
        {
            url = urlAjaxTime+'/selecionar/1/pagina/'+pagina+query;
            ajax(url,'ajax_time');
        }
        else if(tabelas=='funcionario')
        {
            setFiltroFuncionario(null,null,pagina);
        }
        else if(tabelas=='funcionario_adicionados')
        {
            setFiltroFuncionario(null,1,pagina);
        }
        else if(tabelas=='empresas_visiveis')
        {
            setEmpresasVisiveis(1,pagina);
        }    
        else if(tabelas=='times_visiveis')
        {
            setTimesVisiveis(1,pagina);
        }
    }
    
    url = urlAjaxEmpresa+'/selecionar/1';
    ajax(url,'ajax_empresa');
    
    url = urlAjaxTime+'/selecionar/1/';
    ajax(url,'ajax_time');
    
    url = urlAjaxFuncionario+'/adicionar/1/';
    ajax(url,'ajax_funcionario');
    
    url = urlAjaxEmpresa+'/adicionar/1';
    ajax(url,'ajax_empresas_visiveis');
    
    url = urlAjaxTime+'/adicionar/1/';
    ajax(url,'ajax_times_visiveis');
    
    url = urlAjaxGrupo+'/selecionar/1/';
    ajax(url,'ajax_grupo');
    
    carregaMenuTree();
    
</script>