<h3>Cadastro de Empresas</h3>
<hr />
<form name="formulario" id="formulario" action="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'logado', 'action' => 'cadastrarempresa'), null, 1); ?>" method="post">

    <input type="hidden" name="idMatriz" id="idMatriz" value="0" />
    <table  width="100%" height="1318" align="center">
        <tr>
            <td width="30%" align="left">
                <strong>Tipo de empresa:</strong>
            </td>
            <td width="70%" align="left">
                Matriz <input tabindex="1" type="radio" name="tipoEmpresa" id="tipoEmpresa">
                Filial <input tabindex="2" type="radio" name="tipoEmpresa" id="tipoEmpresa" value="1">

                <!-- Div do AJAX´s-->

                <div id="div_tipoEmpresa" class="modal">

                    <!-- Resultado do retorno do AJAX-->                      

                </div>
                <!-- FM da Div do AJAX´s-->
            </td>
        </tr>
        <tr>
            <td align="left">
                Nome Fantasia da Empresa:
            </td>
            <td align="left">
                <input tabindex="3" name="nomeFantasia" id="nomeFantasia" value="" maxlength="100" size="50">

            </td>
        </tr>
        <tr>
            <td align="left">
                Razão Social:
            </td>
            <td align="left">
                <input tabindex="4" name="razaoSocial" id="razaoSocial" value="" maxlength="100" size="50">
            </td>
        </tr>
        <tr>
            <td align="left">
                <div id="nomeMatrizDiv">Nome da Matriz:</div></td>
            <td align="left">
                <div id="nomeMatrizDiv1"><input name="nomeMatriz" id="nomeMatriz" tabindex="5" value="" size="50" maxlength="100"></div>
            </td>
        </tr>            
        <tr>
            <td align="left">
                Apelido:</td>
            <td align="left">
                <input tabindex="6" name="apelido" id="apelido" value="" maxlength="100" size="50">
            </td>
        </tr>
        <tr>
            <td align="left">
                Ramo de atuação: 
            </td>
            <td align="left">
                
                <select tabindex="7" name="idRamoAtuacao" id="idRamoAtuacao" style="width:337px">
                    <option value="">::.. Selecione um Ramo de atuação ..::</option>
                   

                </select>
            </td>
        </tr>
        <tr>
            <td align="left"><label for="numFiliais" id="cpfCnpj">Quantidade de Filiais:</label></td>
            <td align="left">
                <input value="" tabindex="8" name="numFiliais" type="text" id="numFiliais" apelido size="50" maxlength="4"  />
            </td>
        </tr>
        <tr>
            <td align="left"><label for="numFiliais" id="cpfCnpj">CNPJ.:</label></td>
            <td align="left">
                <input value="" tabindex="9" name="cnpj" type="text" id="cnpj" apelido size="50" maxlength="18" />
            </td>
        </tr>
        <tr>
            <td align="left"><label for="ie" id="ie">Inscrição Estadual:</label></td>
            <td align="left">
                <input value="" tabindex="10" name="ie" type="text" id="ie" apelido size="50" maxlength="15" />
            </td>
        </tr>
        <tr><td></td></tr>
        <tr>
            <td align="left" bgcolor="#BBBBBB">
                <b>Endereço</b>
            </td>
        </tr>
        <tr><td></td></tr>
        <tr>
            <td height="26" align="left">
                <label for="cep">CEP</label>
            </td>
            <td align="left">
                <input tabindex="28" name="cep" type="text" id="cep" maxlength="10" size="10" value="" />&nbsp;<input type="button" value="Pesquisar Endereço" id="busend" /></td>
        </tr>
        <tr>
            <td height="26" align="left">
                <label for="endereco">Endereço</label>
            </td>
            <td align="left">
                <input tabindex="11" name="endereco" type="text" id="endereco" maxlength="100" size="28" value="" />                <label for="numero">Número </label>
                <input tabindex="12" name="numero" type="text" id="numero" value="" size="8" maxlength="10" />
            </td>
        </tr>
        <tr>
            <td height="28" align="left">
                <label for="complemento">Complemento</label>
            </td>
            <td align="left">
                <input tabindex="13" name="complemento" type="text" id="complemento" maxlength="100" size="15" value="" />         
                <label for="bairro">Bairro</label>
                <input tabindex="14" name="bairro" type="text" id="bairro" value="" size="23" maxlength="100" />
            </td>
        </tr>
        <tr>
            <td height="26" align="left">
                <label for="cidade">Cidade</label>
            </td>
            <td align="left">
                <input tabindex="15" name="cidade" type="text" id="cidade" maxlength="100" size="34" value="" />        
                <label for="estado">Estado</label>
                <label for="estado"></label>
                <select tabindex="27" name="estado" id="estado" onchange="document.getElementById('cep').focus();">
                    <option value="AC" >AC</option>
                    <option value="AL" >AL</option>
                    <option value="AP" >AP</option>
                    <option value="AM" >AM</option>
                    <option value="BA" >BA</option>
                    <option value="DF" >DF</option>
                    <option value="CE" >CE</option>
                    <option value="ES" >ES</option>
                    <option value="GO" >GO</option>
                    <option value="MA" >MA</option>
                    <option value="MT" >MT</option>
                    <option value="MS" >MS</option>
                    <option value="MG" >MG</option>
                    <option value="PA" >PA</option>
                    <option value="PB" >PB</option>
                    <option value="PR" >PR</option>
                    <option value="PE" >PE</option>
                    <option value="PI" >PI</option>
                    <option value="RJ" >RJ</option>
                    <option value="RS" >RS</option>
                    <option value="RN" >RN</option>
                    <option value="RO" >RO</option>
                    <option value="RR" >RR</option>
                    <option value="SC" >SC</option>
                    <option value="SP" >SP</option>
                    <option value="SE" >SE</option>
                    <option value="TO" >TO</option>
                </select>
            </td>
        </tr>
        <tr>
            <td height="26" align="left">Referência</td>
            <td align="left"><input tabindex="17" name="referencia" type="text" id="referencia" value="" size="23" maxlength="100" />
            </td>
        </tr>
        <tr>
            <td align="left">
                <label for="dddTel">Telefone 1</label>
            </td>
            <td align="left">
                <input tabindex="18" name="dddTel1" id="dddTel1" size="1" maxlength="2" value="" /><input name="telefone1" type="text" id="telefone1" value="" size="13" maxlength="9" />
                <script>// coloar no editar xD selectHabilita('telefone1')</script>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td align="left">
                <label for="dddTel2">Telefone  2</label>
            </td>
            <td align="left">
                <input name="dddTel2" id="dddTel2" tabindex="19" value="" size="1" maxlength="2" /><input name="telefone2" type="text" id="telefone2" value="" size="13" maxlength="9" />
                &nbsp;</td>
        </tr>
        <tr>
            <td align="left">
                <label for="dddTelTemp1">Celular 1</label>
            </td>
            <td align="left">
                <input tabindex="20" name="dddCel1" id="dddCel1" size="1" maxlength="2" value="" /><input name="celular1" type="text" id="celular1" value="" size="13" maxlength="9"/>
                <script>// coloar no editar xD selectHabilita('celular1')</script>
                &nbsp;Operadora:

                <select name="idOperadora1" id="idOperadora1" style="width:220px;">
                    <option value="">::.. Selecione uma Operadora ..::</option>


                </select>
                <script>// coloar no editar xD selectHabilita('celular1')selectHabilita('idOperadora1')</script>
            </td>
        </tr>
        <tr>
            <td align="left">
                <label for="dddCel2">Celular 2</label>
            </td>
            <td align="left">
                <input tabindex="21" name="dddCel2" id="dddCel2" size="1" maxlength="2" value="" /><input name="celular2" type="text" id="celular2" value="" size="13" maxlength="9" />
                <script>// coloar no editar xD selectHabilita('celular2')</script>
                &nbsp;Operadora:

                <select name="idOperadora2" id="idOperadora2" style="width:220px;">
                    <option value="">::.. Selecione uma Operadora ..::</option>
                

                </select>
                <script>// coloar no editar xD selectHabilita('idOperadora2')</script>
            </td>
        </tr>
        <tr>
            <td align="left">
                <label for="dddFax1">Fax1</label>
            </td>
            <td align="left">
                <input tabindex="22" name="dddFax1" id="dddFax1" size="1" maxlength="2" value="" /><input name="fax1" type="text" id="fax1" value="" size="13" maxlength="9" />
                <script>// coloar no editar xD selectHabilita('fax1')</script>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td align="left">
                <label for="dddFax1">Fax 2</label>
            </td>
            <td align="left">
                <input tabindex="23" name="dddFax2" id="dddFax2" size="1" maxlength="2" value="" /><input name="fax2" type="text" id="fax2" value="" size="13" maxlength="9"  />
                <script>// coloar no editar xD selectHabilita('fax2')</script>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td align="left">
                <label for="email">E-mail</label>
            </td>
            <td align="left">
                <input tabindex="24" name="email" onBlur="ValidaEmail(this);" type="text" id="email" maxlength="100" size="50" value="" />
            </td>
        </tr>
        <tr><td></td></tr>
        <tr>
            <td align="left" bgcolor="#BBBBBB">
                <b>Redes Sociais</b>
            </td>
        </tr>
        <tr><td></td></tr>
        <tr>
            <td align="left">
                <label for="site">Home Page:</label>
            </td>
            <td align="left">
                <input tabindex="25" name="site" type="text" id="site" maxlength="100" size="50" value="" />
            </td>
        </tr>
        <tr>
            <td align="left">
                <label for="orkut">Orkut</label>
            </td>
            <td align="left">
                <input name="orkut" tabindex="26" type="text" id="orkut" maxlength="100" size="50" value="" />
            </td>
        </tr>
        <tr>
            <td align="left">
                <label for="site">MSN</label>
            </td>
            <td align="left">
                <input tabindex="27" name="msn" onBlur="ValidaEmail(this);" type="text" id="msn" maxlength="100" size="50" value="" />
            </td>
        </tr>
        <tr>
            <td align="left">
                <label for="twitter">Twitter</label>
            </td>
            <td align="left">
                <input name="twitter" tabindex="28" type="text" id="twitter" maxlength="100" size="50" value="" />
            </td>
        </tr>
        <tr>
            <td align="left">
                <label for="facebook">Facebook</label>
            </td>
            <td align="left">
                <input name="facebook" tabindex="29" type="text" id="facebook" maxlength="100" size="50" value="" />
            </td>
        </tr>
        <tr>
            <td align="left">
                <label for="facebook">Skype</label>
            </td>
            <td align="left">
                <input name="skype" tabindex="29" type="text" id="skype" maxlength="100" size="50" value="" />
            </td>
        </tr>
        <tr><td></td></tr>
        <tr>
            <td align="left" bgcolor="#BBBBBB">
                <b>Detalhes</b>
            </td>
        </tr>
        <tr><td></td></tr>
        <tr>
            <td align="left">
                Pessoa de Contato 1: 
            </td>
            <td align="left">
                <input type="hidden" name="idFuncionario1" id="idFuncionario1" value="" />

                <select tabindex="30" name="idFuncionario1select" id="idFuncionario1select" style="width:337px" onchange="showHint(this.value,'ajax_funcionariosSetor.php?opcao=1','div_Funcionarios1','&');toggleDiv('div_Funcionarios1',1);">
                    <option value="">::.. Selecione um Setor / Unidade de Negócios ..::</option>
                
                </select>
                <!-- Div do AJAX´s-->

                <div id="div_Funcionarios1" class="modal2">

                    <!-- Resultado do retorno do AJAX-->                      

                </div>
                <!-- FM da Div do AJAX´s-->

            </td>                
        </tr>
        <tr>
            <td align="left">
                <label for="nomeTemp1">Nome</label>
                :
            </td>
            <td align="left">
                <input name="nomeTemp1" id="nomeTemp1" value="" size="50" readonly="readonly" style="background-color:#E9E9E9"/>
            </td>
        </tr>
        <tr>
            <td align="left">
                <label for="dddTelTemp1">Telefone</label>
                :
            </td>
            <td align="left">
                <input name="dddTelTemp1" id="dddTelTemp1" value="" size="1" maxlength="2" readonly="readonly" style="background-color:#E9E9E9"/><input name="telefone1Temp" type="text" id="telefone1Temp" value="" size="13" maxlength="9" readonly="readonly" style="background-color:#E9E9E9"/>

            </td>
        </tr>
        <tr>
            <td align="left">
                <label for="dddTelTemp1">Celular</label>
                :
            </td>
            <td align="left">
                <input name="dddCelTemp1" id="dddCelTemp1" value="" size="1" maxlength="2" readonly="readonly" style="background-color:#E9E9E9"/><input name="celularTemp1" type="text" id="celularTemp1" value="" size="13" maxlength="9" readonly="readonly" style="background-color:#E9E9E9"/>
                &nbsp;Operadora:
                <input name="operadoraTemp1" type="text" id="operadoraTemp1" value="" readonly="readonly" style="background-color:#E9E9E9" />

            </td>
        </tr>
        <tr>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td align="left">
                Pessoa de Contato 2: 
            </td>
            <td align="left">
                <input type="hidden" name="idFuncionario2" id="idFuncionario2" value="" />

                <select tabindex="31" name="idFuncionario2select" id="idFuncionario2select" style="width:337px" onchange="showHint(this.value,'ajax_funcionariosSetor.php?opcao=2','div_Funcionarios2','&');toggleDiv('div_Funcionarios2',1);">
                    <option value="">::.. Selecione um Setor / Unidade de Negócios ..::</option>


                </select>
                <!-- Div do AJAX´s-->

                <div id="div_Funcionarios2" class="modal2">

                    <!-- Resultado do retorno do AJAX-->                      

                </div>
                <!-- FM da Div do AJAX´s-->
            </td>
        </tr>
        <tr>
            <td align="left">
                <label for="nomeTemp2">Nome</label>
                :
            </td>
            <td align="left">
                <input name="nomeTemp2" id="nomeTemp2" value="" size="50" readonly="readonly" style="background-color:#E9E9E9"/>
            </td>
        </tr>
        <tr>
            <td align="left">
                <label for="dddTelTemp1">Telefone</label>
                :
            </td>
            <td align="left">
                <input name="dddTelTemp2" id="dddTelTemp2" value="" size="1" maxlength="2" readonly="readonly" style="background-color:#E9E9E9"/><input name="telefone2Temp" type="text" id="telefone2Temp" value="" size="13" maxlength="9" readonly="readonly" style="background-color:#E9E9E9"/>

            </td>
        </tr>
        <tr>
            <td align="left">
                <label for="dddTelTemp1">Celular</label>
                :
            </td>
            <td align="left">
                <input name="dddCelTemp2" id="dddCelTemp2" value="" size="1" maxlength="2" readonly="readonly" style="background-color:#E9E9E9"/><input name="celularTemp2" type="text" id="celularTemp2" value="" size="13" maxlength="9" readonly="readonly" style="background-color:#E9E9E9"/>

                &nbsp;Operadora:
                <input name="operadoraTemp2" type="text" id="operadoraTemp2" value="" readonly="readonly" style="background-color:#E9E9E9" />

            </td>
        </tr>
        <tr>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td align="left">
                <label for="facebook">Número de Funcionários:</label></td>
            <td align="left">
                <select tabindex="32" onchange="document.getElementById('idCategoria_cliente').focus();" name="numFuncionarios" id="numFuncionarios" style="width:337px">
                    <option value="-1">::.. Selecione ..::</option>
                    <option value="0">até 10</option>
                    <option value="1">20</option>
                    <option value="2">50</option>
                    <option value="3">100</option>
                    <option value="4">200</option>
                    <option value="5">500</option>
                    <option value="6">1000</option>
                    <option value="7">2000</option>
                    <option value="8">+ de 2000</option>

                </select>
            </td>
        </tr>
        <tr>
            <td align="left">
                Categoria: 
            </td>
            <td align="left">

                <select tabindex="33" onchange="document.getElementById('status').focus();" name="idCategoria_cliente" id="idCategoria_cliente" style="width:337px">
                    <option value="">::.. Selecione uma Categoria ..::</option>

                </select>
            </td>
        </tr>
        <tr>
            <td align="left">
                Status: 
            </td>
            <td align="left">
                <input tabindex="34" type="radio" name="status" id="status" value="1" maxlength="1" />&nbsp;ATIVO<input type="radio" name="status" id="status" value="0" maxlength="1" />&nbsp;INATIVO
            </td>
        </tr>
        <tr>
            <td colspan="2" align="center">&nbsp;

            </td>
        </tr>
        <tr>
            <td colspan="2" align="center">&nbsp;

            </td>
        </tr>
        <tr>
            <td colspan="2" align="center">
                <input name="btnCadastrar" type="submit" id="btnCadastrar" value="Cadastrar" onclick="javascript:verifica_tds_campos('formulario')" />&nbsp;</td>
        </tr>
        <tr>
            <td colspan="2" align="center">&nbsp;

            </td>
        </tr>
        <tr>
            <td colspan="2" align="center">&nbsp;

            </td>
        </tr>
        <tr>
            <td colspan="2" align="center">&nbsp;

            </td>
        </tr>
        <tr>
            <td colspan="2" align="center">&nbsp;

            </td>
        </tr>




    </table>
</form>

