
<h3>Cadastro de Funcionário</h3>
<i class="icon-asterisk"></i> Campos obrigatórios.
<hr />

<div id="funcionario">
<form class="form-inline" name="formulario" id="formulario" action="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'logado', 'action' => 'ajaxgravafuncionario'), null, 1); ?>" method="post" >
    <table  width="100%" height="1318" align="center">
        <tr>
            <td width="30%" align="left">
                    <strong>Tipo de empresa:</strong>
            </td>
            <td width="70%" align="left">
                <label class="radio inline">
                    <input type="radio" name="tipoEmpresa" id="tipoEmpresa" value="0" onclick="abreDialog('0');">Matriz
                </label>
                <label class="radio inline">
                    <input type="radio" name="tipoEmpresa" id="tipoEmpresa" value="1" onclick="abreDialog('1');">Filial
                </label>
                <p id="p_empresa" class="radio inline"><i class="icon-asterisk"></i></p>
                
            </td>
        </tr>
        <tr>
            <td align="left">
                    Nome Fantasia da Empresa:
            </td>
            <td align="left">
                <input disabled="disabled" name="nomeFantasia" id="nomeFantasia" type="text" value="::.. Selecione um tipo de Empresa ..::" maxlength="100" size="50">
                
            </td>
        </tr>
        <tr>
            <td align="left">
                   <!-- Nome do Time:-->
            </td>
            <td align="left">
                <input disabled="disabled" name="nomeTime" id="nomeTime" type="hidden" value="::.. Selecione um Time ..::" maxlength="100" size="50" >&nbsp;
                <input type="hidden" name="btTime" id="btTime" value="Escolher Time" onclick="abreDialogTime();" class="btn btn-info"/>
                               
            </td>
        </tr>
        <tr>
            <td align="left">
                    Nome Completo:
            </td>
            <td align="left">
                    <input tabindex="1" name="nome" id="nome" type="text" value="" maxlength="100" size="50" />
            </td>
        </tr>
        <tr>
            <td align="left">
                    Conhecido por:
            </td>
            <td align="left">
                    <input tabindex="2" type="text" name="apelido" id="apelido" value="" maxlength="100" size="50">
            </td>
        </tr>
        <tr >
            <td id="div_FiltroFuncionrio" colspan="2">
            </td>        
        </tr>
        <tr>
            <td align="left">
                <label for="cnpjCpf" id="cpfCnpj">CPF</label>                
                <a href="javascript:;" class="showToolTip" title="Este campo será usado como login do funcionário.">
                    <img src="<?php echo $this->baseUrl()."/public/images/sistema/help.ico"; ?>" width="20px" higth="20px">
                </a>
            </td>
            <td align="left">
                    <input tabindex="6" name="cpf" type="text" id="cpf" value="" size="50" maxlength="14" onkeyup="MascaraCpfCnpj(this,event);" onblur="checaCpf(this.value)"/>
                    <p id="p_cpf" class="radio inline"><i class="icon-asterisk"></i></p>
            </td>
        </tr>
        <tr>
            <td align="left">
                Data de Admissão:
            </td>
            <td align="left">
                <input tabindex="7" type="text" name="data_admissao" id="data_admissao" class="calendario" value=""/>
            </td>
        </tr>
        <tr>
            <td align="left">
                Data no Setor:
            </td>
            <td align="left">
                    <input tabindex="8" type="text" name="data_setor" id="data_setor" class="calendario" value=""/>
            </td>
        </tr>
        <tr>
            <td align="left">
                Data de Nascimento:
            </td>
            <td align="left">
                    <input tabindex="9" type="text" name="data_nascimento" id="data_nascimento" class="calendario" value=""/>
            </td>
        </tr>
        <tr>
            <td align="left">
                AVISAR À GERENCIA?
            </td>
            <td align="left">
                <label class="radio inline">    
                    <input tabindex="10" type="radio" name="avisar_pinho_marcia" id="avisar_pinho_marcia" value="1" maxlength="1"/>&nbsp;SIM
                </label>
                <label class="radio inline">
                    <input type="radio" name="avisar_pinho_marcia" id="avisar_pinho_marcia" value="0"  maxlength="1"/>&nbsp;NÃO
                </label>
            </td>
        </tr>
        <tr>
            <td align="left">
                Sexo:
            </td>
            <td align="left">
                <label class="radio inline">    
                    <input tabindex="10" type="radio" name="sexo" id="sexo" value="0"  maxlength="1"/>&nbsp;M&nbsp;&nbsp;&nbsp;
                </label>
                <label class="radio inline">
                    <input type="radio" name="sexo" id="sexo" value="1" maxlength="1"/>&nbsp;F
                </label>
            </td>
        </tr>
        <tr>
            <td align="left">
                    <label for="dddTel">Telefone Residêncial 1</label>
            </td>
            <td align="left">
                <input tabindex="11" name="dddTelRes1" id="dddTelRes1" style="width:30px" type="text" value="" maxlength="2" onkeyup="maskIt(this,event,'##');ativaProximo(this, 'telefoneRes1');"/>&nbsp;
                <input name="telefoneRes1" type="text" id="telefoneRes1" value="" size="13" maxlength="9" onblur="validaTelefone(this);" onkeyup="maskIt(this,event,'####-####');proximoCampo(this, 'dddTelRes2')" readonly="readonly" style="background-color:#E9E9E9" />
            &nbsp; 
            </td>
        </tr>
        <tr>
            <td align="left">
                <label for="dddTel2">Telefone Residêncial 2</label>
            </td>
            <td align="left">
                    <input name="dddTelRes2" id="dddTelRes2" tabindex="12" style="width:30px" value="" type="text" maxlength="2" onkeyup="maskIt(this,event,'##');ativaProximo(this, 'telefoneRes2');"/>&nbsp;
                    <input name="telefoneRes2" type="text" id="telefoneRes2"  value="" size="13" maxlength="9" readonly="readonly" style="background-color:#E9E9E9" onblur="validaTelefone(this);" onkeyup="maskIt(this,event,'####-####');proximoCampo(this, 'dddCel1')"/>
            &nbsp; </td>
        </tr>
        <tr>
            <td align="left">
                    <label for="dddCel1">Celular 1</label>
            </td>
            <td align="left">
                    <input tabindex="13" name="dddCel1" id="dddCel1"  maxlength="2" style="width:30px" value="" type="text" onkeyup="maskIt(this,event,'##');ativaProximo(this, 'celular1');habilitaSelect(this,'id_operadora_celular',0)"/>&nbsp;
                    <input name="celular1" type="text" id="celular1" value="" size="13" maxlength="9" readonly="readonly" style="background-color:#E9E9E9" onblur="validaTelefone(this);" onkeyup="maskIt(this,event,'####-####')"/>
                &nbsp;Operadora:

                <select disabled="disabled"  name="id_operadora_celular" id="id_operadora_celular" style="width:220px">
                    <option value="">::.. Selecione uma Operadora ..::</option>
                        <?php
                        foreach ($this->operadoras as $operadora){
                        ?>
                            <option value="<?php echo $operadora['id_operadora_celular']?>"><?php echo $operadora['titulo']?></option>
                        <?php
                        }
                        ?>
                    </option>


                </select>
            </td>
        </tr>
        <tr>
            <td align="left">
                    <label for="dddCel2">Celular 2</label>
            </td>
            <td align="left">
                    <input tabindex="14" name="dddCel2" id="dddCel2" maxlength="2" style="width:30px" value="" type="text" onkeyup="maskIt(this,event,'##');ativaProximo(this, 'celular2');habilitaSelect(this,'id_operadora_celular2',0)"/>&nbsp;
                    <input name="celular2" type="text" id="celular2"  value="" size="13" maxlength="9" readonly="readonly" style="background-color:#E9E9E9" onblur="validaTelefone(this);" onkeyup="maskIt(this,event,'####-####')"/>
                &nbsp;Operadora:

                <select disabled="disabled"  name="id_operadora_celular2" id="id_operadora_celular2" style="width:220px">
                    <option value="">::.. Selecione uma Operadora ..::</option>
                        <?php
                        foreach ($this->operadoras as $operadora){
                        ?>
                            <option value="<?php echo $operadora['id_operadora_celular']?>"><?php echo $operadora['titulo']?></option>
                        <?php
                        }
                        ?>

                    </option>


                </select>
            </td>
        </tr>
        <tr>
            <td align="left">
                    <label for="dddCel3">Celular 3</label>
            </td>
        <td align="left">
                    <input tabindex="15" name="dddCel3" id="dddCel3"  maxlength="2" style="width:30px" value="" type="text" onkeyup="maskIt(this,event,'##');ativaProximo(this, 'celular3');habilitaSelect(this,'id_operadora_celular3',0)"/>&nbsp;
                    <input name="celular3" type="text" id="celular3" value="" size="13" maxlength="9" readonly="readonly" style="background-color:#E9E9E9" onblur="validaTelefone(this);" onkeyup="maskIt(this,event,'####-####')"/>
                &nbsp;Operadora:

                <select disabled="disabled" name="id_operadora_celular3" id="id_operadora_celular3" >
                    <option value="">::.. Selecione uma Operadora ..::</option>
                        <?php
                        foreach ($this->operadoras as $operadora){
                        ?>
                            <option value="<?php echo $operadora['id_operadora_celular']?>"><?php echo $operadora['titulo']?></option>
                        <?php
                        }
                        ?>

                    </option>


                </select>
            </td>
        </tr>
        <tr>
            <td align="left">
                    <label for="email2">E-mail da Empresa</label>
                    <a href="javascript:;" class="showToolTip" title="Este campo será usado como login do funcionário.">
                    <img src="<?php echo $this->baseUrl()."/public/images/sistema/help.ico"; ?>" width="20px" higth="20px">
                </a>
            <td align="left">
                <input tabindex="16" name="email_empresa" type="email" id="email_empresa" maxlength="100" size="50" value="" onblur="checaEmail(this.value)" />
                    <p id="p_email" class="radio inline"><i class="icon-asterisk"></i></p>
            </td>
        </tr>
        <tr>
            <td align="left">
                    <label for="email2">E-mail Pessoal</label></td>
            <td align="left">
                    <input tabindex="16" name="email_pessoal_1" type="email" id="email_pessoal_1" maxlength="100" size="50" value="" onblur="checaEmail(this.value)"/>
        </td>
        </tr>
        <tr>
            <td align="left">
            <label for="email2">E-mail Pessoal</label></td>
            <td align="left">
                    <input tabindex="16" name="email_pessoal_2"  type="email" id="email_pessoal_2" maxlength="100" size="50" value="" onblur="checaEmail(this.value)"/>
            </td>
        </tr>
        <tr><td></td></tr>
        <tr>
            <td align="left" bgcolor="#BBBBBB">
                    <b>Redes Sociais</b>
            </td>
        </tr>
        <tr><td></td></tr>
        <tr>
            <td align="left">
                    <label for="msn">MSN</label>
            </td>
            <td align="left">
                    <input tabindex="17" name="msn" type="text" id="msn" maxlength="100" size="50" value="" />
            </td>
        </tr>
        <tr>
            <td align="left">
                    <label for="skype">Skype</label>
            </td>
            <td align="left">
                    <input name="skype" tabindex="18" type="text" id="skype" maxlength="100" size="50" value="" />
            </td>
        </tr>
        <tr>
            <td align="left">
                    <label for="orkut">Orkut</label>
            </td>
            <td align="left">
                    <input name="orkut" tabindex="19" type="text" id="orkut" maxlength="100" size="50" value="" />
            </td>
        </tr>
        <tr>
            <td align="left">
                    <label for="facebook">Facebook</label>
            </td>
            <td align="left">
                    <input name="facebook" tabindex="20" type="text" id="facebook" maxlength="100" size="50" value="" />
            </td>
        </tr>
        <tr>
            <td align="left">
                    <label for="twitter">Twitter</label>
            </td>
            <td align="left">
                    <input name="twitter" tabindex="21" type="text" id="twitter" maxlength="100" size="50" value="" />
            </td>
        </tr>
        <tr><td></td></tr>
        <tr>
            <td align="left" bgcolor="#BBBBBB">
                    <b>Endereço</b>
            </td>
        </tr>
        <tr><td></td></tr>
        <tr>
            <td height="26" align="left">
                    <label for="cep">CEP</label>
            </td>
            <td align="left">
                <input tabindex="28" name="cep" type="text" id="cep" maxlength="10" size="10" value="" onkeyup="proximoCampo(this, 'busend');maskIt(this,event,'##.###-###')" onblur="validaCep(this);buscaCep('funcionario');"/>&nbsp;
                <input type="button" value="Pesquisar Endereço" id="busend" class="btn btn-info" onclick="buscaCep('funcionario');"/>
            </td>
        </tr>
        <tr>
            <td height="26" align="left">
                    <label for="endereco">Endereço</label>
            </td>
            <td align="left">
                <input tabindex="22" name="tipo_logradouro" type="text" id="tipo_logradouro" maxlength="100" size="28" value="" />
                Número:
                <input tabindex="23" name="numero" type="text" id="numero" value="" style="width:50px" maxlength="10" />
            </td>
        </tr>
        <tr>
            <td height="28" align="left">
                    <label for="complemento">Complemento</label>
            </td>
            <td align="left">
                <input tabindex="24" name="complemento" type="text" id="complemento" maxlength="100" size="15" value="" />
            </td>
        </tr>
        <tr>
            <td height="28" align="left">
                    <label for="complemento">Bairro</label>
            </td>
            <td align="left">
                <input tabindex="25" name="bairro" type="text" id="bairro" value="" size="23" maxlength="100" />
            </td>
        </tr>
        <tr>
            <td height="26" align="left">
                    <label for="cidade">Cidade</label>
            </td>
            <td align="left">
                <input tabindex="26" name="cidade" type="text" id="cidade" maxlength="100" size="34" value="" />        
                Estado:
                <select tabindex="27" name="estado" id="estado" style="width:70px">
                    <option value="AC">AC</option>
                    <option value="AL">AL</option>
                    <option value="AP">AP</option>
                    <option value="AM">AM</option>
                    <option value="BA">BA</option>
                    <option value="DF">DF</option>
                    <option value="CE">CE</option>
                    <option value="ES">ES</option>
                    <option value="GO">GO</option>
                    <option value="MA">MA</option>
                    <option value="MT">MT</option>
                    <option value="MS">MS</option>
                    <option value="MG">MG</option>
                    <option value="PA">PA</option>
                    <option value="PB">PB</option>
                    <option value="PR">PR</option>
                    <option value="PE">PE</option>
                    <option value="PI">PI</option>
                    <option value="RJ" selected="selected">RJ</option>
                    <option value="RS">RS</option>
                    <option value="RN">RN</option>
                    <option value="RO">RO</option>
                    <option value="RR">RR</option>
                    <option value="SC">SC</option>
                    <option value="SP">SP</option>
                    <option value="SE">SE</option>
                    <option value="TO">TO</option>
                </select>
            </td>
        </tr>
        <tr>
            <td height="26" align="left">Referência</td>
            <td align="left"><input tabindex="29" name="referencia" type="text" id="referencia" value="" size="23" maxlength="100" />
            </td>
        </tr>
        
        
        
        
        <tr>
            <td align="left">
                    Categoria: 
            </td>
            <td align="left">

                <select tabindex="48" name="id_categoria" id="id_categoria" style="width:220px">
                    <option value="">::.. Selecione uma Categoria ..::</option>
                        <?php
                        foreach ($this->categorias as $categoria){
                        ?>
                            <option value="<?php echo $categoria['id_categoria_empresa']?>"><?php echo $categoria['titulo']?></option>
                        <?php
                        }
                        ?>

                </select>
            </td>
        </tr>
        <tr>
            <td align="left">
                Status: 
            </td>
            <td align="left">
                <label class="radio inline">
                    <input tabindex="49" type="radio" name="status" id="status" value="1" maxlength="1"/>&nbsp;ATIVO
                </label>    
                <label class="radio inline">
                    <input type="radio" name="status" id="status" value="0" maxlength="1" />&nbsp;INATIVO
                </label>
                <p id="p_ativo" class="radio inline"><i class="icon-asterisk"></i></p>
            </td>
        </tr>
        <tr>
            <td colspan="2" align="center">&nbsp;

            </td>
        </tr>
        <tr>
            <td colspan="2" align="center">&nbsp;

            </td>
        </tr>
        
        
    </table>
    <div align="center" class="form-actions" id="salva">
        <input type="button" class="btn btn-success" onclick="valida();" value="Gravar">
    </div>
    <div id="dialog-modal-empresa" title="Selecione uma empresa">
        <div id="ajax_empresa" onmouseover="setTabela('empresa');"></div>
    </div>
    <div id="dialog-modal-time" title="Selecione um time">
        <div id="ajax_time" onmouseover="setTabela('time');"></div>
    </div>
    <input type="hidden" name="arrayIdTempEmpresa" id="arrayIdTempEmpresa" value=",">
    <input type="hidden" name="arrayIdTempTime" id="arrayIdTempTime" value=",">
    
    <?php //campos a serem gravados  ?>
    <input type="hidden" name="id_empresa" id="id_empresa" value=",">
    <input type="hidden" name="id_time" id="id_time" value=",0,">
    <input type="hidden" name="tel_residencial_1" id="tel_residencial_1" value="">
    <input type="hidden" name="tel_residencial_2" id="tel_residencial_2" value="">
    <input type="hidden" name="celular_1" id="celular_1" value="">
    <input type="hidden" name="celular_2" id="celular_2" value="">
    <input type="hidden" name="celular_3" id="celular_3" value="">
</form>
</div>
<style>
    .ui-tooltip, .arrow:after {
        background: black;
        border: 2px solid white;
    }
    .ui-tooltip {
        padding: 10px 20px;
        color: white;
        border-radius: 20px;
        font: bold 14px "Helvetica Neue", Sans-Serif;
        text-transform: uppercase;
        box-shadow: 0 0 7px black;
    }
    .arrow {
        width: 70px;
        height: 16px;
        overflow: hidden;
        position: absolute;
        left: 50%;
        margin-left: -35px;
        bottom: -16px;
    }
    .arrow.top {
        top: -16px;
        bottom: auto;
    }
    .arrow.left {
        left: 20%;
    }
    .arrow:after {
        content: "";
        position: absolute;
        left: 20px;
        top: -20px;
        width: 25px;
        height: 25px;
        box-shadow: 6px 5px 9px -9px black;
        -webkit-transform: rotate(45deg);
        -moz-transform: rotate(45deg);
        -ms-transform: rotate(45deg);
        -o-transform: rotate(45deg);
        tranform: rotate(45deg);
    }
    .arrow.top:after {
        bottom: -20px;
        top: auto;
    }
</style>

<script>
    varTipoEmpresa = '';
        
    $(function() {
        $( ".showToolTip" ).tooltip({
            position: {
                my: "center bottom-20",
                at: "center top",
                using: function( position, feedback ) {
                    $( this ).css( position );
                    $( "<div>" )
                        .addClass( "arrow" )
                        .addClass( feedback.vertical )
                        .addClass( feedback.horizontal )
                        .appendTo( this );
                }
            }
        });
    });
    $(document).ready(function() {
        document.getElementById('p_cargo').innerHTML = '<i class="icon-asterisk"></i>';
        document.getElementById('p_setor').innerHTML = '<i class="icon-asterisk"></i>';
        document.getElementById('p_tipo').innerHTML  = '<i class="icon-asterisk"></i>';
        
    });
    
    function reiniciaEstados(){
        //reinicia os estados
        document.getElementById('cpf').style.borderColor = "";
        document.getElementById('p_cpf').innerHTML = '<i class="icon-asterisk"></i>';
        document.getElementById('p_empresa').innerHTML = '<i class="icon-asterisk"></i>';
        document.getElementById('id_setor').style.borderColor = "";
        document.getElementById('p_setor').innerHTML = '<i class="icon-asterisk"></i>';
        document.getElementById('id_cargo').style.borderColor = "";
        document.getElementById('p_cargo').innerHTML = '<i class="icon-asterisk"></i>';
        document.getElementById('id_funcionario_tipo').style.borderColor = "";
        document.getElementById('p_tipo').innerHTML = '<i class="icon-asterisk"></i>';
        document.getElementById('email_empresa').style.borderColor = "";
        document.getElementById('p_email').innerHTML = '<i class="icon-asterisk"></i>';
        document.getElementById('p_ativo').innerHTML = '<i class="icon-asterisk"></i>';
    }
    
    function prepara(){
        document.getElementById('tel_residencial_1').value = document.getElementById('dddTelRes1').value+document.getElementById('telefoneRes1').value;
        document.getElementById('tel_residencial_2').value = document.getElementById('dddTelRes2').value+document.getElementById('telefoneRes2').value;
        document.getElementById('celular_1').value = document.getElementById('dddCel1').value+document.getElementById('celular1').value;
        document.getElementById('celular_2').value = document.getElementById('dddCel2').value+document.getElementById('celular2').value;
        document.getElementById('celular_3').value = document.getElementById('dddCel3').value+document.getElementById('celular3').value;
                
        document.getElementById('cpf').value = removeCaractere(document.getElementById('cpf').value);
        document.getElementById('data_admissao').value = converteDataMysql(document.getElementById('data_admissao').value);
        document.getElementById('data_setor').value = converteDataMysql(document.getElementById('data_setor').value);
        document.getElementById('data_nascimento').value = converteDataMysql(document.getElementById('data_nascimento').value);
        document.getElementById('cep').value = removeCaractere(document.getElementById('cep').value);
        document.getElementById('tel_residencial_1').value = removeCaractere(document.getElementById('tel_residencial_1').value);
        document.getElementById('tel_residencial_2').value = removeCaractere(document.getElementById('tel_residencial_2').value);
        document.getElementById('celular_1').value = removeCaractere(document.getElementById('celular_1').value);
        document.getElementById('celular_2').value = removeCaractere(document.getElementById('celular_2').value);
        document.getElementById('celular_3').value = removeCaractere(document.getElementById('celular_3').value);
    }
    
    flag = 1;
    
    function checaCpf(valor){
        valor = removeCaractere(valor);
        document.getElementById('p_cpf').innerHTML = '&nbsp<i class="icon-asterisk"></i>';
        
        if(ValidarCPF(document.getElementById('cpf')))
            ajax(urlAjaxValidaUsuario+'/cpf/'+valor, 'p_cpf');
        
        temp = document.getElementById('p_cpf').innerHTML
        if(temp.indexOf("existe") != -1)
        {    
            flag = 0;
        }
        
        
    }
    
    function checaEmail(valor){
        
        document.getElementById('p_email').innerHTML = '&nbsp<i class="icon-asterisk"></i>';
        
        if(validarEmail(document.getElementById('email_empresa').value))
            ajax(urlAjaxValidaUsuario+'/email/'+valor, 'p_email');
        
        temp = document.getElementById('p_email').innerHTML
        
        if(temp.indexOf("existe") != -1)
        {    
            flag = 0;
        }
        
            
    }
    
    function valida(){
        flag = 1;
        reiniciaEstados();
        prepara();
        checaCpf(document.getElementById('cpf').value);
        checaEmail(document.getElementById('email_empresa').value);
        
        if(document.getElementById('id_empresa').value == ",")
        {
            flag = 0;
            document.getElementById('p_empresa').innerHTML = '<font color="#ff0000"><i class="icon-asterisk"></i>&nbsp;<font color="#ff0000">Campo Obrigatório!</font>';
        }
        
        if( (document.getElementById('cpf').value == "") || (!ValidarCPF(document.getElementById('cpf'))))
        {
            flag = 0;
            document.getElementById('cpf').style.borderColor = "#ff0000";
            document.getElementById('p_cpf').innerHTML = '<i class="icon-asterisk"></i>&nbsp;<font color="#ff0000">Campo Obrigatório!</font>';
        }
        
        if(document.getElementById('email_empresa').value == "")
        {
            flag = 0;
            document.getElementById('email_empresa').style.borderColor = "#ff0000";
            document.getElementById('p_email').innerHTML = '<i class="icon-asterisk"></i>&nbsp;<font color="#ff0000">Campo Obrigatório!</font>';

        }
        
        if(!validarEmail(document.getElementById('email_empresa').value))
        {
            flag = 0;
        }
        
        if(document.getElementById('id_setor').value == "")
        {
            flag = 0;
            document.getElementById('id_setor').style.borderColor = "#ff0000";
            document.getElementById('p_setor').innerHTML = '<i class="icon-asterisk"></i>&nbsp;<font color="#ff0000">Campo Obrigatório!</font>';
            
        }
        
        if(document.getElementById('id_cargo').value == "")
        {
            flag = 0;
            document.getElementById('id_cargo').style.borderColor = "#ff0000";
            document.getElementById('p_cargo').innerHTML = '<i class="icon-asterisk"></i>&nbsp;<font color="#ff0000">Campo Obrigatório!</font>';
        }
        
        if(document.getElementById('id_funcionario_tipo').value == "")
        {
            flag = 0;
            document.getElementById('id_funcionario_tipo').style.borderColor = "#ff0000";
            document.getElementById('p_tipo').innerHTML = '<i class="icon-asterisk"></i>&nbsp;<font color="#ff0000">Campo Obrigatório!</font>';
        }
        
        radio = document.getElementsByTagName("input");
        blnFlag = false;
        
        for(i=0; i<radio.length; i++) // percorre os radios e verifica qual radio está marcado
        {
            if (radio[i].getAttribute("type") == "radio" && radio[i].checked == true && radio[i].name == "status") // se for input do tipo radio e estiver marcado
            {
                blnFlag = true;
            }
        }
        
        if(!blnFlag)
        {
            flag = 0;
            document.getElementById('status').style.borderColor = "#ff0000";
            document.getElementById('p_ativo').innerHTML = '<i class="icon-asterisk"></i>&nbsp;<font color="#ff0000">Campo Obrigatório!</font>';
        }
        
        //Se validou
        if(flag){
            ajaxJQuery('funcionario');
            document.getElementById('salva').innerHTML = '<font color="green">Salvo!</font>';
            
            document.getElementById('cpf').value = colocaMascaraCpf(document.getElementById('cpf').value);
            document.getElementById('cep').value = colocaMascaraCep(document.getElementById('cep').value);
            document.getElementById('tel_residencial_1').value = colocaMascaraTel(document.getElementById('tel_residencial_1').value);
            document.getElementById('tel_residencial_2').value = colocaMascaraTel(document.getElementById('tel_residencial_2').value);
            document.getElementById('celular_1').value = colocaMascaraTel(document.getElementById('celular_1').value);
            document.getElementById('celular_2').value = colocaMascaraTel(document.getElementById('celular_2').value);
            document.getElementById('celular_3').value = colocaMascaraTel(document.getElementById('celular_3').value);
            document.getElementById('data_admissao').value = converteDataTela(document.getElementById('data_admissao').value);
            document.getElementById('data_setor').value = converteDataTela(document.getElementById('data_setor').value);
            document.getElementById('data_nascimento').value = converteDataTela(document.getElementById('data_nascimento').value);
        }    
        else
            showAlert('Atenção','Verifique no formulário os campos indicados.');
    }
    
    function setNomeFantasia()
    {
        idEmpresa = document.getElementById('arrayIdTempEmpresa').value;
        idEmpresa = idEmpresa.substr(1,idEmpresa.length-2);
        
        if(idEmpresa)
            document.getElementById('nomeFantasia').value = document.getElementById('nomefantasia_'+idEmpresa).value;
    }
    
    function setNomeTime()
    {
        idTime = document.getElementById('arrayIdTempTime').value;
        idTime = idTime.substr(1,idTime.length-2);
        
        if(idTime)
            document.getElementById('nomeTime').value = document.getElementById('nometime_'+idTime).value;
    }
    
    function setPaginator(pagina,query)
    {  
        //tabelas é setado ao passar o mouse sobre a DIV        
        if(tabelas=='empresa')
        {   
            document.getElementById('ajax_empresa').innerHTML = '';
            url = urlAjaxEmpresa+'/escolher/1/pagina/'+pagina+query+'/tipoEmpresa/'+varTipoEmpresa;
            ajax(url,'ajax_empresa');
        }
        if(tabelas=='time')
        {   
            document.getElementById('ajax_time').innerHTML = '';
            url = urlAjaxTime+'/escolher/1/pagina/'+pagina+query;
            ajax(url,'ajax_time');
        }
    }   
    
    //exibe uma modal para que o usuario escolha uma empresa
    function abreDialog(tipoEmpresa)
    {
        varTipoEmpresa = tipoEmpresa;
        
        url = urlAjaxEmpresa+'/escolher/1/tipoEmpresa/'+varTipoEmpresa;
        ajax(url,'ajax_empresa');
        
        $( "#dialog-modal-empresa" ).dialog({
            modal: true,
            width: 822,
            buttons: {
                Ok: function() {
                    temp = document.getElementsByClassName('idEmpresaTempe');
                    if(temp.length)
                    { 
                        for (i = 0; i < temp.length; i++)
                        {   
                            if(temp[i].checked)
                            {    
                                document.getElementById('id_empresa').value = temp[i].value;
                                setNomeFantasia();
                                break;
                            }    
                        }
                    }
                    
                    $( this ).dialog( "close" );
                    
                }
            }
        });
    }
    
    //exibe uma modal para que o usuario escolha uma empresa
    function abreDialogTime()
    {        
        url = urlAjaxTime+'/escolher/1';
        ajax(url,'ajax_time');
        
        $( "#dialog-modal-time" ).dialog({
            modal: true,
            width: 822,
            buttons: {
                Ok: function() {
                    temp = document.getElementsByClassName('idTimeTempe');
                    if(temp.length)
                    { 
                        for (i = 0; i < temp.length; i++)
                        {   
                            if(temp[i].checked)
                            {    
                                setNomeTime();
                                document.getElementById('id_time').value = temp[i].value;
                                break;
                            }    
                        }
                    }
                   
                    $( this ).dialog( "close" );
                    
                }
            }
        });
    }
    
    url = urlAjaxFiltroSCT+'/setor/1/cargo/1/tipo/1';
    ajax(url,'div_FiltroFuncionrio');
    
</script>    