
<?php
    /* * *
    * Carrega o menu tree baseado nas permissoes do usuario
    */

    $_SESSION['menuTree'] = null;
    unset($_SESSION['menuTree']);

    $_SESSION['menuTree'] = '';
    $_SESSION['menuTree'] .= '<ul id="treemenu1" class="treeview">'."\n";
    
    function montaMenuTree($id_funcionalidade,$resultado,$url,$cont)
    {
        foreach ($resultado as $value) 
        {
            $cont++;
            if ($value['id_funcionalidade_pai']==$id_funcionalidade)
            {
                
                if($value['action']=='')
                {
                    $estilo = '';
                    if($value['titulo']=='Cadastrar' || $value['titulo']=='Gerenciar')
                        $estilo = "class='modal_auto_size'";
                    
                    $_SESSION['menuTree'] .= "<li>".$value['titulo']."\n";
                        $_SESSION['menuTree'] .=  "<ul><div id='tree_$cont' class='modal_auto_size'>\n";
                }
                else
                {                    
                    $style = '';
                    
                    $editar = '';
                    if(!$value['editar'])
                        $style = 'style="display:none"';
                    $editar = '<span '.$style.'>&nbsp;&nbsp;Editar&nbsp;<input class="idFuncionalidade" type="checkbox" id="funcionalidade_editar" name="funcionalidade_editar[]" value="'.$value['editar'].'" onclick="setGrupoOff();"></span>';
                    
                    $style = '';
                    $deletar = '';
                    if(!$value['deletar'])
                        $style = 'style="display:none"';
                    $deletar = '<span '.$style.'>&nbsp;&nbsp;Deletar&nbsp;<input class="idFuncionalidade" type="checkbox" id="funcionalidade_deletar" name="funcionalidade_deletar[]" value="'.$value['deletar'].'" onclick="setGrupoOff();"></span>';
                    
                    $style = '';
                    $liberar = '';
                    if(!$value['liberar'])
                        $style = 'style="display:none"';
                    $liberar = '<span '.$style.'>&nbsp;&nbsp;Liberar&nbsp;<input class="idFuncionalidade" type="checkbox" id="funcionalidade_liberar" name="funcionalidade_liberar[]" value="'.$value['liberar'].'" onclick="setGrupoOff();"></span>';
                    
                    $seta='';
                    if($value['editar'] || $value['deletar'] || $value['liberar'])
                        $seta = '<i class="icon-arrow-right"></i>';
                    
                    $_SESSION['menuTree'] .= '<li style="clear:both;"><div class="funcionalidade"><input class="idFuncionalidade" type="checkbox" id="id_funcionalidades" name="id_funcionalidades[]" value="'.$value['id_funcionalidade'].'" onclick="setGrupoOff();">&nbsp;&nbsp;'.$value['titulo']."</div><div class='funcionalidade2'>$seta&nbsp;$editar$deletar$liberar</div></li>\n";
                }
                
                //echo $value['titulo']." ".$value['action']."\n";
                
                montaMenuTree($value['id_funcionalidade'],$resultado,$url,$cont);//,$menu);
                
                if($value['action']=='')
                {
                    $_SESSION['menuTree'] .= "</div></ul>\n";
                    $_SESSION['menuTree'] .= "</li>\n";
                }
            }
        }
        
    }
    
    montaMenuTree(0,$this->permissoes,$this->url(array('module' => 'sistema', 'controller' => 'logado', 'action' => ''), null, 1),1);
    
    $_SESSION['menuTree'] .= '</ul>';
    
    
    echo $_SESSION['menuTree'];
    