<h3>Editar de Controle de Acesso</h3>
<hr>
<div id="tabs" style="width:811px;">  
    <form name="formularioCarregaMenu" action="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'logado', 'action' => 'ajaxgravacontroleacesso'), null, 1); ?>" method="post">
        <ul>
            <li><a href="#tabs-4">Empresas Visíveis</a></li>
            <li><a href="#tabs-5">Times Visíveis</a></li>
            <li><a href="#tabs-6">Funcionalidades</a></li>
        </ul>
                
        <div id="tabs-4" class="tab_content">
            <h4>Escolha as Empresas Visiveis</h4>

            <div id="ajax_empresas_visiveis" class="modal_ajax" onmouseover="setTabela('empresas_visiveis');">
            </div>

            <h4>Empresas Escolhidas</h4>

            <div id="ajax_empresas_adicionadas" class="modal_ajax" onmouseover="setTabela('empresas_adicionadas');">
            </div>

        </div>
        <div id="tabs-5" class="tab_content">
            <h4>Escolha os Times Visiveis</h4>

            <div id="ajax_times_visiveis" class="modal_ajax" onmouseover="setTabela('times_visiveis');">
            </div>

            <h4>Times Escolhidos</h4>

            <div id="ajax_times_adicionados" class="modal_ajax" onmouseover="setTabela('times_adicionados');">
            </div>
        </div>
        <div id="tabs-6" class="tab_content">
            <div class="modal_filtro">
                <h3>Funcionalidades</h3>
                <hr>
                <strong>Escolha as funcionalidades que serão liberadas para os funcionários escolhidos.<br>
                Você tem a opção te escolher um grupo de funcionalidades ou escolher cada funcionalidade uma a uma.<br>
                Lembrando que, ou você escolhe grupos ou diretamente as funcionalidades.<br></strong>
                <hr>
                <h4>Grupos</h4>
                <div id="ajax_grupo" class="modal_ajax">
                </div>
                <h4>Funcionalidades</h4>
                <div id="ajax_funcionalidades" class="modal_min_auto_size">

                </div>
            </div>
        </div>    

        <!-- campos hidden temporarios -->
        <input type="hidden" name="arrayIdTempEmpresa" id="arrayIdTempEmpresa" value=",">
        <input type="hidden" name="arrayIdTempTime"    id="arrayIdTempTime" value=",">
        <input type="hidden" name="arrayIdTempFuncionarioEscolhido"    id="arrayIdTempFuncionarioEscolhido" value=",<?php echo $this->idFuncionario; ?>,">
        <input type="hidden" name="arrayIdTempEmpresaEscolhida"    id="arrayIdTempEmpresaEscolhida" value=",">
        <input type="hidden" name="arrayIdTempTimeEscolhido"    id="arrayIdTempTimeEscolhido" value=",">
        <div id="ajax_id_funcionalidade" style="display: none"></div>
    
    </div><!--<div id="tab">-->
    <div align="center" class="form-actions">
        <input type="button" class="btn btn-success" onclick="valida();" value="Editar">
    </div>
        
    </form>
    
</div>

<?php
    $listaIdEmpresa = ",";
    foreach ($this->arrayIdEmpresa as $linha)
    {    
        $listaIdEmpresa .= $linha['id_empresa'].",";
    }
    
    $listaIdTime = ",";
    foreach ($this->arrayIdTime as $linha)
    {    
        $listaIdTime .= $linha['id_time'].",";
    }
    
?>

<script type="text/javascript">      
    
    function valida()
    {
        flag=1
        textoMsgErro = '';

        if(document.getElementById('arrayIdTempFuncionarioEscolhido').value == ",")
        {
            flag = 0;
            textoMsgErro += 'Não há Funcionários escolhidos!<br>';
        }

        if(document.getElementById('arrayIdTempTimeEscolhido').value == ",")
        {
            flag = 0;
            textoMsgErro += 'Não há Times Visiveis escolhidos!<br>';
        }

        if(document.getElementById('arrayIdTempEmpresaEscolhida').value == ",")
        {
            flag = 0;
            textoMsgErro += 'Não há Empresas Visiveis escolhidas!<br>';
        }

        if ($('#idGrupoTmp')[0])
        {    
            
            flag1=0;
            flag2=0;
            
            temps = document.forms[0].getElementsByClassName('idGrupoTmp');
            if(temps.length)
            { 
                for (j = 0; j < temps.length; j++)
                {   //alert(temp.length);
                    if(temps[j].checked)
                        flag1=1;
                }
            }
            
            temps = document.forms[0].getElementsByClassName('idFuncionalidade');
            if(temps.length)
            { 
                for (j = 0; j < temps.length; j++)
                {   //alert(temp.length);
                    if(temps[j].checked)
                        flag2=1;
                }
            }
                        
            if(flag1==0 && flag2==0)
            {
                flag = 0;
                textoMsgErro += 'Não há Funcionalidades escolhidas!<br>';
            }
        }
        else
        {
            flag1=0;
            temps = document.forms[0].getElementsByClassName('idFuncionalidade');
            if(temps.length)
            { 
                for (j = 0; j < temps.length; j++)
                {   //alert(temp.length);
                    if(temps[j].checked)
                        flag1 = 1;
                }
            }
            if(flag1==0)
            {
                flag = 0;
                textoMsgErro += 'Não há Funcionalidade escolhida!<br>';
            }            
        }

        if(flag)
        {            
            temps = document.forms[0].getElementsByClassName('idFuncionalidade');
            desmarcaPai();

            if(temps.length)
            { 
                for (j = 0; j < temps.length; j++)
                {   //alert(temp.length);
                    if(temps[j].checked)
                        marcaPai(temps[j].value);
                }
            }

            carregaGravando();
        }
        else
            showAlert('Atenção',textoMsgErro);

    }    
    
    //ao clicar nos botoes do paginator, essa funcao eh chamada e um determinado
    // ajax eh excudado
    function setPaginator(pagina,query)
    {  
        if(tabelas=='empresa')
        {    
            url = urlAjaxEmpresa+'/selecionar/1/pagina/'+pagina+query;
            ajax(url,'ajax_empresa');
        }
        else if(tabelas=='time')
        {
            url = urlAjaxTime+'/selecionar/1/pagina/'+pagina+query;
            ajax(url,'ajax_time');
        }else if(tabelas=='empresas_visiveis')
        {
            setEmpresasVisiveis(1,pagina);
        }    
        else if(tabelas=='times_visiveis')
        {
            setTimesVisiveis(1,pagina);
        }
    } 
        
    url = urlAjaxEmpresa+'/adicionar/1';
    ajax(url,'ajax_empresas_visiveis');
    
    url = urlAjaxTime+'/adicionar/1/';
    ajax(url,'ajax_times_visiveis');
    
    <?php
        $urlGrupo = "";
        if($this->arrayIdGrupo)
            $urlGrupo = 'editarCA/1/id_usuario/'.$this->id_usuario;
            
    ?>
    url = urlAjaxGrupo+'/selecionar/1/<?php echo $urlGrupo; ?>';
    ajax(url,'ajax_grupo');
    
    <?php
        if($urlGrupo)
            $urlGrupo = 0;
        else
            $urlGrupo = 1;            
    ?>
    //alert(<?php echo $urlGrupo; ?>);
    
    carregaMenuTree('<?php echo $urlGrupo; ?>','<?php echo $this->id_usuario ?>');
    
    if(!<?php echo $urlGrupo; ?>)
    {    
        temps = document.forms[0].getElementsByClassName('idGrupoTmp');
        if(temps.length)
        { 
            for (j = 0; j < temps.length; j++)
            {   //alert(temp.length);
                if(temps[j].checked)
                    carregaMenuTree();getIdFuncionalidade(temps[j].value);setFuncioGrupo();disableLED();
            }
        }
    }
    
    ddtreemenu.flatten('treemenu1', 'expand');
    
    document.getElementById('arrayIdTempEmpresaEscolhida').value = '<?php echo $listaIdEmpresa?>';
    
    setEmpresasVisiveis(1,'');
    setEmpresasVisiveis('',1);
    
    document.getElementById('arrayIdTempTimeEscolhido').value = '<?php echo $listaIdTime?>';
    
    setTimesVisiveis(1,'');
    setTimesVisiveis('',1);
</script>
