<h3><p id="nomeGrupo">Editar Grupo de Acesso: <?php echo $this->nomeGrupo; ?></p></h3>

<div id="funcionalidade">
    <form name="formularioCarregaMenu" action="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'logado', 'action' => 'ajaxgravagrupo','idGrupo'=>$this->idGrupo), null, 1); ?>" method="post">
       
        <div class="modal_filtro">
            <h4>Nome do Grupo</h4>
            <div align="center" class="form-actions">
                <input name="nome" id="nome" value="<?php echo $this->nomeGrupo; ?>" placeholder="Nome do Grupo">
            </div>
            <h4>Funcionalidades</h4>
            <strong>
                Escolha as funcionalidades que serão liberadas para o grupo a ser criado.<br>
            </strong>
            <hr>
            <div id="ajax_funcionalidades" class="modal_min_auto_size">
            </div>
        </div>
           

        <!-- campos hidden temporarios -->
        
        <div id="ajax_id_funcionalidade" style="display: none"></div>    
    
        <div align="center" class="form-actions">
            <input type="button" class="btn btn-success" onclick="valida();" value="Editar">
        </div>        
    </form>
</div>    

<script>
    listaIdFuncionalidade = '<?php echo $this->listaIdFuncionalidade;?>';
    
    function valida()
    {
        flag=1
        textoMsgErro = '';

        if(document.getElementById('nome').value == "")
        {
            flag = 0;
            textoMsgErro += 'Preencha o nome do Grupo de Acesso!<br>';
        }
                
        flag1=0;
        temps = document.forms[0].getElementsByClassName('idFuncionalidade');
        if(temps.length)
        { 
            for (j = 0; j < temps.length; j++)
            {   //alert(temp.length);
                if(temps[j].checked)
                    flag1 = 1;
            }
        }
        if(flag1==0)
        {
            flag = 0;
            textoMsgErro += 'Não há Funcionalidade escolhida!<br>';
        } 
        
        //Se validou
        if(flag)
        {            
            temps = document.forms[0].getElementsByClassName('idFuncionalidade');
            desmarcaPai();

            if(temps.length)
            { 
                for (j = 0; j < temps.length; j++)
                {   //alert(temp.length);
                    if(temps[j].checked)
                        marcaPai(temps[j].value);
                }
            }
            
            //grava
            ajaxJQuery('funcionalidade');
            
            document.getElementById('nomeGrupo').innerHTML = 'Editar Grupo de Acesso: '+document.getElementById('nome').value; 
        }
        else
            showAlert('Atenção.',textoMsgErro);
        
    }    
    
    carregaMenuTree();
    
    function recarrega(){
        arrayIdFuncionalidades = '';
        temps = document.forms[0].getElementsByClassName('idFuncionalidade');
        if(temps.length)
        { 
            for (j = 0; j < temps.length; j++)
            {   //alert(temp.length);
               
                idFuncionalidade = temps[j].value;
                idFuncionalidade = idFuncionalidade.substr(idFuncionalidade.indexOf(',')+1)
                arrayIdFuncionalidades = listaIdFuncionalidade.split(",");
                
                for (m = 0; m < arrayIdFuncionalidades.length; m++)
                {
                    if(arrayIdFuncionalidades[m] == idFuncionalidade)
                    {    
                        temps[j].checked  = true;
                        toggleLED(idFuncionalidade);
                    }    
                }
            }
        }
    }
    
    recarrega();
    ddtreemenu.flatten('treemenu1', 'expand');
    
</script>    