<h3>Gerenciar Funcionário</h3>
<hr>
<form name="formularioCarregaMenu" action="" method="post">
    <div class="modal_min_auto_size">
    
        <h4>Filtros:</h4>
                        <label for="cnpjCpf" id="cpfCnpj">CNPJ</label>
                <input value="" tabindex="9" name="cnpj" type="text" id="cnpj" size="20" maxlength="18" class="input-medium search-query" onkeyup="MascaraCpfCnpj(this,event);"/>
        <input type="button" onclick="filtraCnpj();" value="Filtrar por CNPJ"  />
        &nbsp;&nbsp;&nbsp;<input type="radio" name="todos" id="todos" onclick="setFiltroFuncionario('todos');apagaArrayIdTempTime();setFiltroTime();" checked="checked" /> 
        <b>Exibir todas as empresas</b>
        <hr>
        <h5>Empresa</h5>
        <div id="ajax_empresa" class="modal_ajax" onmouseover="setTabela('empresa');">    
        </div>
        <hr>
        <h5>Time</h5>
        <div id="ajax_time" class="modal_ajax" onmouseover="setTabela('time');">    
        </div>

        <div id="div_FiltroFuncionrio" class="modal_filtro">
            
        </div>        
    </div>
    <hr>
    <h4>Funcionário:</h4>
    <div id="ajax_funcionario" class="modal_ajax" onmouseover="setTabela('funcionario');">    
    </div>
    <input type="hidden" name="arrayIdTempFuncionario"    id="arrayIdTempFuncionario" value=",">
    <input type="hidden" name="arrayIdTempEmpresa" id="arrayIdTempEmpresa" value=",">
    <input type="hidden" name="arrayIdTempTime"    id="arrayIdTempTime" value=",">
    <input type="hidden" name="arrayIdTempFuncionarioEscolhido"    id="arrayIdTempFuncionarioEscolhido" value=",">
        
</form>
<div id="temp"></div>

<script type="text/javascript">      
    
    //set o "selectOrAdd" como 2 para não exibir
    selectOrAdd = 2;
    //set o "gerenciarFuncionario" para editar e deletar
    gerenciarFuncionario = 1;
    
    //ao clicar nos botoes do paginator, essa funcao eh chamada e um determinado
    // ajax eh excudado
    function setPaginator(pagina,query)
    {  
        if(tabelas=='empresa')
        {    
            url = urlAjaxEmpresa+'/selecionar/1/pagina/'+pagina+query;
            ajax(url,'ajax_empresa');
        }
        else if(tabelas=='time')
        {
            url = urlAjaxTime+'/selecionar/1/pagina/'+pagina+query;
            ajax(url,'ajax_time');
        }    
        else if(tabelas=='funcionario')
        {
            url = urlAjaxFuncionario+'/selecionar/1/pagina/'+pagina+query;
            ajax(url,'ajax_funcionario');
        }
    }
            
    url = urlAjaxEmpresa+'/selecionar/1';
    ajax(url,'ajax_empresa');
    
    url = urlAjaxTime+'/selecionar/1/';
    ajax(url,'ajax_time');
    
    LED = '';    
    <?php
        $aux = '';
        
        if($this->editar)
          $aux .= '/editar/1';
        
        if($this->deletar)
          $aux .= '/deletar/1' 
    ?>
        
    function deletar(idFuncionario)
    {
        url = '<?php echo $this->url(array('module' => 'sistema', 'controller' => 'logado', 'action' => 'deletarfuncionario'), null, 1); ?>/idFuncionario/'+idFuncionario;
        ajax(url,'temp');
        
        url = urlAjaxFuncionario+'<?php echo $aux; ?>';
        ajax(url,'ajax_funcionario');
        
    }    

    url = urlAjaxFuncionario+'<?php echo $aux; ?>';
    ajax(url,'ajax_funcionario');
    
    url = urlAjaxFiltroSCT+'/setor/1/cargo/1/tipo/1';
    ajax(url,'div_FiltroFuncionrio');
       
    urlAjaxFuncionario+='<?php echo $aux; ?>';
</script>