<h3>Genrenciar Funcionario</h3>
<hr>
<form name="formularioCarregaMenu" action="" method="post">
    <div class="modal_min_auto_size">
    
        <h4>Filtros:</h4>
        CNPJ: &nbsp;&nbsp;&nbsp;&nbsp;
        <input value="" tabindex="9" name="cnpj" type="text" id="cnpj" size="20" maxlength="18" class="input-medium search-query" />
        <input type="button" onclick="filtraCnpj();" value="Filtrar por CNPJ"  />
        &nbsp;&nbsp;&nbsp;<input type="radio" name="todos" id="todos" onclick="setFiltroFuncionario('todos');apagaArrayIdTempTime();setFiltroTime();" checked="checked" /> 
        <b>Exibir todas as empresas</b>
        <hr>
        <h5>Empresa</h5>
        <div id="ajax_empresa" class="modal_ajax" onmouseover="setTabela('empresa');">    
        </div>
        <hr>
        <h5>Time</h5>
        <div id="ajax_time" class="modal_ajax" onmouseover="setTabela('time');">    
        </div>

        <div id="div_FiltroFuncionrio" class="modal_filtro">
            <table align="center">	
                <tr>
                    <td align="left">
                        Setor / Unidade de Negócios: 
                    </td>
                    <td align="left">
                        <select tabindex="30" name="idSetor" id="idSetor" style="width:370px" onchange="setFiltroFuncionario();">
                            <option value="">::.. Selecione um Setor / Unidade de Negócios (TODOS) ..::</option>
                            <?php
                            foreach ($this->arraySetor as $linha) {
                                ?>
                                <option value="<?php echo $linha['id_setor']; ?>"><?php echo $linha['titulo']; ?></option>
                                <?php
                            }
                            ?>

                        </select>
                    </td>
                </tr>
                <tr>
                    <td align="left">
                        Cargo: 
                    </td>
                    <td align="left">
                        <select tabindex="4" name="idCargo" id="idCargo" style="width:370px" onchange="setFiltroFuncionario();">
                            <option value="">::.. Selecione um Cargo (TODOS) ..::</option>
                            <?php
                            foreach ($this->arrayCargo as $linha) {
                                ?>
                                <option value="<?php echo $linha['id_cargo']; ?>" ><?php echo $linha['titulo']; ?></option>
                                <?php
                            }
                            ?>                            
                        </select>
                    </td>
                </tr>
                <tr>
                    <td align="left">
                        Tipo: 
                    </td>
                    <td align="left">
                        <select tabindex="5" name="idFuncionario_tipo" id="idFuncionario_tipo" style="width:370px" onchange="setFiltroFuncionario();" >
                            <option value="">::.. Selecione um Tipo (TODOS) ..::</option>
                            <?php
                            foreach ($this->arrayFuncionario_tipo as $linha) {
                                ?>
                                <option value="<?php echo $linha['id_funcionario_tipo']; ?>" ><?php echo $linha['titulo']; ?></option>
                                <?php
                            }
                            ?>                            
                        </select>
                    </td>
                </tr>
            </table>
        </div>        
    </div>
    <hr>
    <h4>Funcionário:</h4>
    <div id="ajax_funcionario" class="modal_ajax" onmouseover="setTabela('funcionario');">    
    </div>
    <input type="hidden" name="arrayIdTempFuncionario"    id="arrayIdTempFuncionario" value=",">
    <input type="hidden" name="arrayIdTempEmpresa" id="arrayIdTempEmpresa" value=",">
    <input type="hidden" name="arrayIdTempTime"    id="arrayIdTempTime" value=",">
    <input type="hidden" name="arrayIdTempFuncionarioEscolhido"    id="arrayIdTempFuncionarioEscolhido" value=",">
    <div align="center" class="form-actions">
        <?php
            if(isset($this->arrayControlAcessLED['editar']))
                echo '<input type="button" class="btn btn-primary" onclick="valida();" value="Editar">';
            echo ' &nbsp; &nbsp;';
            if(isset($this->arrayControlAcessLED['deletar']))
                echo '<input type="button" class="btn btn-danger" onclick="valida();" value="Deletar">';

        ?>
        
    </div>
    
</form>

<script type="text/javascript">      
    
    //set o "selectOrAdd" para selecionar
    selectOrAdd = 1;
    
    //ao clicar nos botoes do paginator, essa funcao eh chamada e um determinado
    // ajax eh excudado
    function setPaginator(pagina,query)
    {  
        if(tabelas=='empresa')
        {    
            url = urlAjaxEmpresa+'/selecionar/1/pagina/'+pagina+query;
            ajax(url,'ajax_empresa');
        }
        else if(tabelas=='time')
        {
            url = urlAjaxTime+'/selecionar/1/pagina/'+pagina+query;
            ajax(url,'ajax_time');
        }    
        else if(tabelas=='funcionario')
        {
            url = urlAjaxFuncionario+'/selecionar/1/pagina/'+pagina+query;
            ajax(url,'ajax_funcionario');
        }
    }
    
    url = urlAjaxEmpresa+'/selecionar/1';
    ajax(url,'ajax_empresa');
    
    url = urlAjaxTime+'/selecionar/1/';
    ajax(url,'ajax_time');
        
    url = urlAjaxFuncionario+'/selecionar/1/';
    ajax(url,'ajax_funcionario');
       
    
</script>