<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>PINHONLINE</title>
                
        <link href="<?php echo $this->baseUrl()."/public/styles/portal/estilo.css"; ?>" type="text/css" rel="stylesheet" />
        <script type="text/javascript" src="<?php echo $this->baseUrl()."/public/scripts/portal/jquery.js"; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl()."/public/scripts/portal/font.js"; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl()."/public/scripts/portal/load.js"; ?>"></script>

        <script src="<?php echo $this->baseUrl()."/public/scripts/portal/ui/jquery.selectbox.js"; ?>"></script>
        <script src="<?php echo $this->baseUrl()."/public/scripts/portal/ui/jquery.maskedinput-1.3.min.js"; ?>"></script>
                
        <!-- datapicker -->

        <link rel="stylesheet" href="<?php echo $this->baseUrl()."/public/scripts/portal/ui/development-bundle/themes/base/jquery.ui.all.css"; ?>">

        <script src="<?php echo $this->baseUrl()."/public/scripts/portal/ui/development-bundle/ui/jquery.ui.datepicker.js"; ?>"></script>
        <script src="<?php echo $this->baseUrl()."/public/scripts/portal/ui/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js"; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl()."/public/scripts/portal/browserDetect.js"; ?>"></script>

        <script src="<?php echo $this->baseUrl()."/public/scripts/portal/jquery.nyroModal.custom.min.js"; ?>"></script>
        <script src="<?php echo $this->baseUrl()."/public/scripts/portal/jquery.nyroModal-ie6.min.js"; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl()."/public/scripts/portal/valida.js"; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl()."/public/scripts/portal/valida.config.js"; ?>"></script>

        <script>
        $(function() {
            $("#datepicker").datepicker({ firstDay: 1 , showWeek: true });
        });
        </script>

        <script>
            jQuery(document).ready(function(){jQuery("#formCadastro").validationEngine(); });
        </script>
        
        <link href="<?php echo $this->baseUrl()."/library/Plugins/jqueryui/css/smoothness/jquery-ui-1.9.1.custom.css"; ?>" rel="stylesheet" type="text/css" />
        
        <script type="text/javascript" src="<?php echo $this->baseUrl()."/library/Plugins/jqueryui/js/jquery-ui-1.9.1.custom.js"; ?>"></script>
                        
        <script type="text/javascript" src="<?php echo $this->baseUrl()."/public/scripts/utilitario.js" ?>"></script>
        
        <!--forca da senha-->
        <script src="<?php echo $this->baseUrl()."/public/scripts/portal/pschecker.js"; ?>"></script>

    </head>
    <?php
        
        if( $this->linkAtivo == 'index')     $linkAtivo1 = 'linkAtivo'; else $linkAtivo1 = '';
        if( $this->linkAtivo == 'quemsomos') $linkAtivo2 = 'linkAtivo'; else $linkAtivo2 = '';
        if( $this->linkAtivo == 'solucoes')  $linkAtivo3 = 'linkAtivo'; else $linkAtivo3 = '';
        if( $this->linkAtivo == 'servicos')   $linkAtivo4 = 'linkAtivo'; else $linkAtivo4 = '';
        if( $this->linkAtivo == 'contato')   $linkAtivo5 = 'linkAtivo'; else $linkAtivo5 = '';
        if( $this->linkAtivo == 'extras')    $linkAtivo6 = 'linkAtivo'; else $linkAtivo6 = '';
            
    ?>
    
    <body class="<?php
        $link = $this->linkAtivo;
        
        if($link == "contato" ) { echo $link; } 
        elseif($link == "solucoes" ) { echo $link; }
        elseif($link == "servicos" ) { echo $link; }
        else  { echo 'portal'; }
        
    ?>">
       <?php  
            //Caso tenha dado erro, fica na session.
            ZendUtils::receptorMsg();   
        ?>

        <div id="preloader"></div>

        <div class="documento">
            <div class="menu">
                <div><a href="<?php echo $this->url(array('module'=>'portal', 'controller'=>'index','action'=>'index'),null,1); ?>" class="logo linkAtivoLogo">&nbsp;</a></div>
                <div><a class=" <?php echo $linkAtivo1; ?> " href="<?php echo $this->url(array('module'=>'portal', 'controller'=>'index','action'=>'index'),null,1); ?>">inicio</a></div>
                <div><a class=" <?php echo $linkAtivo2; ?> " href="<?php echo $this->url(array('module'=>'portal', 'controller'=>'index','action'=>'quemsomos'),null,1); ?>">quem somos</a></div>
                <div><a class=" <?php echo $linkAtivo3; ?> " href="<?php echo $this->url(array('module'=>'portal', 'controller'=>'index','action'=>'solucoes'),null,1); ?>">soluções</a></div>
                <div><a class=" <?php echo $linkAtivo4; ?> " href="<?php echo $this->url(array('module'=>'portal', 'controller'=>'index','action'=>'servicos'),null,1); ?>">serviços</a></div>
                <div><a class=" <?php echo $linkAtivo5; ?> " href="<?php echo $this->url(array('module'=>'portal', 'controller'=>'index','action'=>'contato'),null,1); ?>">contato</a></div>
                <div><a class=" <?php echo $linkAtivo6; ?> " href="<?php echo $this->url(array('module'=>'portal', 'controller'=>'index','action'=>'extras'),null,1); ?>">extras</a></div>       
            </div>
            <div class="gadget">
                <div class="item login">
                    <div class="gadgetTopo">
                        <h5>login</h5>
                    </div>
                    <div class="section">
                        <br />

                        <!-- caro programador, a validação já está funcionando,
                        os input's obrigatóriamente deverão ter um ID, todas páginas deverão ser estáticas, 
                        ou seja, sem modal, para evitar problemas crossbrowzer, thanks :) -->

                        <form id="formLogin" action="<?php echo $this->url(array('module'=>'portal', 'controller'=>'index','action'=>'logar'),null,1); ?>" method="post" name="formLogin">
                            <table cellpadding="0" cellspacing="0" border="0">
                                <tr>
                                    <td>usuário</td>
                                </tr>
                                <tr>
                                    <td><input id="login" name="login" class="login validate[required],minSize[2]" type="text" /></td>
                                </tr>
                                <tr class="base">
                                    <td>senha</td>
                                </tr>
                                <tr>
                                    <td><input id="senha" name="senha" class="login validate[required],minSize[6]" type="password" /></td>
                                </tr>
                                <tr class="base">
                                    <td><button class="full" type="submit">Acessar</button></td>
                                </tr>
                                <tr class="base">
                                    <td><div id="recuperarSenha"><a href="<?php echo $this->url(array('module'=>'portal', 'controller'=>'index','action'=>'recuperarsenha'),null,1); ?>">Recuperar Senha ou Usuário</a></div></td>
                                </tr>
                            </table>
                        </form>
                    </div>
                </div>
                <div class="item social">
                    <div class="gadgetTopo">
                        <h5>Redes Sociais</h5>
                    </div>
                    <div class="section">
                        <table>
                            <tr>
                                <td>
                                    <a href="#help" class="modal" onMouseOver="$('#i1').show();" onMouseOut="$('#i1').hide();">
                                        <img src="<?php echo $this->baseUrl()."/public/images/portal/icone/msn.png"; ?>" />
                                    </a>
                                </td>	
                                <td>
                                    <a href="#help2" class="modal" onMouseOver="$('#i2').show();" onMouseOut="$('#i2').hide();">
                                        <img src="<?php echo $this->baseUrl()."/public/images/portal/icone/skype.png"; ?>" />
                                    </a>
                                </td>
                                <td>
                                    <a href="http://twitter.com/#!/fandopinho" target="_blank" onMouseOver="$('#i3').show();" onMouseOut="$('#i3').hide();">
                                        <img src="<?php echo $this->baseUrl()."/public/images/portal/icone/twitter.png"; ?>" />
                                    </a>
                                </td>
                                <td>
                                    <a href="http://twitter.com/#!/pinhoshow" target="_blank" onMouseOver="$('#i4').show();" onMouseOut="$('#i4').hide();">
                                        <img src="<?php echo $this->baseUrl()."/public/images/portal/icone/twitter.png"; ?>" />
                                    </a>
                                </td>
                                <td>
                                    <a href="#help3" class="modal" onMouseOver="$('#i5').show();" onMouseOut="$('#i5').hide();">
                                        <img src="<?php echo $this->baseUrl()."/public/images/portal/icone/facebook.png"; ?>" />
                                    </a>
                                </td>
                                <td>
                                    <a href="#help4" class="modal" onMouseOver="$('#i6').show();" onMouseOut="$('#i6').hide();">
                                        <img src="<?php echo $this->baseUrl()."/public/images/portal/icone/orkut.png"; ?>" />
                                    </a>
                                </td>
                            </tr>
                        </table>
                        <table class="legenda">
                            <tr>
                                <td id="i1">MSN</td> 
                                <td id="i2">Skype</td>
                                <td id="i3">Twitter FandoPinho</td>
                                <td id="i4">Twitter Pinhoshow</td>
                                <td id="i5">Facebook</td>
                                <td id="i6">Orkut</td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="item calendario">
                    <div class="gadgetTopo">
                        <h5>calendário</h5>
                    </div>
                    <div class="section2">
                        <div id="datepicker"></div>
                    </div>
                </div>
                <div class="item social">
                    <div class="gadgetTopo" style="background-image:none;">
                    </div>
                    <div class="section">
                        <a href="http://www.criweb.com.br" target="_blank">Desenvolvimento <strong>Criweb</strong></a>
                    </div>
                </div>
            </div>
            <div class="conteudo <?php
                
                if($link == "contato") { echo "contato"; }
                if($link == "servicos") { echo "servicos"; }
                ?>">

                <?php echo $this->layout()->content; ?>
                
            </div>
            <div class="rodape">
            </div>
            <div class="clear"></div>
        </div>

        <div id="help" style="display:none;"> 
            <div class="helpTable">
                <span class='helpHead'></span>
                <span class="helpBox">
                    <img src="<?php echo $this->baseUrl()."/public/images/portal/geral/pinhonet.png"; ?>" style="float:left;"/> 
                    <div class="msgNyro">
                        <p>
                            Entre em contato com seu Pinhonet!
                        </p>
                        <p>
                            <br /><br />
                            <a href="#" class="button nyroModalCloseButton nyroModalClose" style="margin-left:50px;">continuar</a>
                        </p>
                    </div>
                </span>
            </div>
        </div>


        <div id="help2" style="display:none;"> 
            <div class="helpTable">
                <span class='helpHead'></span>
                <span class="helpBox">
                    <img src="<?php echo $this->baseUrl()."/public/images/portal/geral/pinhonet.png"; ?>" style="float:left;"/> 
                    <div class="msgNyro">
                        <p>
                            Entre em contato com seu Pinhonet!
                        </p>
                        <p>
                            <br /><br />
                            <a href="#" class="button nyroModalCloseButton nyroModalClose" style="margin-left:50px;">continuar</a>
                        </p>
                    </div>
                </span>
            </div>
        </div>


        <div id="help3" style="display:none;"> 
            <div class="helpTable">
                <span class='helpHead'></span>
                <span class="helpBox">
                    <img src="<?php echo $this->baseUrl()."/public/images/portal/geral/pinhonet.png"; ?>" style="float:left;"/> 
                    <div class="msgNyro">
                        <p>
                            Entre em contato com seu Pinhonet!
                        </p>
                        <p>
                            <br /><br />
                            <a href="#" class="button nyroModalCloseButton nyroModalClose" style="margin-left:50px;">continuar</a>
                        </p>
                    </div>
                </span>
            </div>
        </div>


        <div id="help4" style="display:none;"> 
            <div class="helpTable">
                <span class='helpHead'></span>
                <span class="helpBox">
                    <img src="<?php echo $this->baseUrl()."/public/images/portal/geral/pinhonet.png"; ?>" style="float:left;"/> 
                    <div class="msgNyro">
                        <p>
                            Entre em contato com seu Pinhonet!
                        </p>
                        <p>
                            <br /><br />
                            <a href="#" class="button nyroModalCloseButton nyroModalClose" style="margin-left:50px;">continuar</a>
                        </p>
                    </div>
                </span>
            </div>
        </div>


        <script type="text/javascript">
            $(function() {
                $('.modal').nyroModal({
                    closeButton: '<a href="#" class="nyroModalClose nyroModalCloseButton nmReposition" title="close">Fechar</a>'
                });
            });
        </script>

    </body>
</html>