<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="<?php echo $this->baseUrl()."/library/Plugins/jqueryui/css/smoothness/jquery-ui-1.9.1.custom.css"; ?>" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="<?php echo $this->baseUrl()."/library/Plugins/jqueryui/js/jquery-1.8.2.js"; ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl()."/library/Plugins/jqueryui/js/jquery-ui-1.9.1.custom.js"; ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl()."/library/Plugins/jquery.limit-1.2.source.js"; ?>"></script>

    <script type="text/javascript" src="<?php echo $this->baseUrl()."/public/scripts/utilitario.js" ?>"></script>
    <style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 0px; padding: 0px }
      #map_canvas { height: 100% }

    </style>

    <script type="text/javascript">

        //coordenadas de Nova Friburgo, RJ, Brasil
        var lat = -22.28736;
        var lng = -42.533698;
        var raio = 100;// raido de pesquisa em metros
        var id_categoria = 0;
        var circulo = '';
        var map = null;
        var markerEstouAqui = []; //array com o marker da localizacao do user
        var markerOferta    = []; //array com o(s) marker(s) de cada oferta

        //  seta a variavel global raio
        function setRaio(paramRaio)
        {
            raio = parseInt(paramRaio);//converte string em inteiro. Na verdade, converte qq tipo em inteiro
            initialize();
            document.getElementById('id_categoria_oferta').value = id_categoria;
            document.getElementById('txRaio').value = raio;
        }
        
        function setFiltro(paramId_categoria){
            id_categoria = parseInt(paramId_categoria);//converte string em inteiro. Na verdade, converte qq tipo em inteiro
            initialize();
            document.getElementById('id_categoria_oferta').value = id_categoria;
        }

        /**
         * O RaioControle adciona um controle no mapa, que setara o
         * raio de busca da pesquisa. Este construtor recebe uma DIV
         * como um argumento.
         * o nome dessa funcao DEVE!!! comecar com letra maiuscula
         */
        function RaioControle(controlDiv, map) 
        {	
            // Css da DIV q contem o controle
            controlDiv.style.padding = '5px';

            // Css da borda do controle e do titulo q sera exibido ao passa o mouse sobre o controle
            var controlUI = document.createElement('DIV');
            controlUI.style.backgroundColor = 'white';
            controlUI.style.borderStyle = 'solid';
            controlUI.style.borderWidth = '2px';
            controlUI.style.cursor = 'pointer';
            controlUI.style.textAlign = 'center';
            controlUI.title = 'Informe o Raio de Busca';
            controlUI.id = 'raioBusca';
            controlDiv.appendChild(controlUI);

            // CSS para o interior do controle
            var controlText = document.createElement('DIV');
            controlText.style.fontFamily = 'Arial,sans-serif';
            controlText.style.fontSize = '12px';
            controlText.style.paddingLeft = '4px';
            controlText.style.paddingRight = '4px';
            controlText.innerHTML = '<input type="text" size="12"  placeholder="Raio em Metros" id="txRaio""><input type="button" value="Raio" id="btRaio" onClick="setRaio(document.getElementById(\'txRaio\').value);"><br>';
            
            <?php
                $select = '';
                $select .="<select name='id_categoria_oferta' id='id_categoria_oferta' style='width:220px' onChange='setFiltro(this.value);'>";
                $select .=    "<option value=''>::.. Selecione uma Categoria ..::</option>";
                
                        foreach ($this->categoria_oferta as $categoria_oferta){
                        
                           $select .=" <option value='".$categoria_oferta['id_categoria_oferta']."'>".$categoria_oferta['titulo']."</option>";
                        
                        }                        
            
                $select .='</select>';
                
            ?>
            
            controlText.innerHTML += "<?php echo $select;?>";
            controlUI.appendChild(controlText);	

        }

        /**
         * O Carregando adciona um controle no mapa, que exibira uma DIV "Pesquisando..."
         * o nome dessa funcao DEVE!!! comecar com letra maiuscula
         */
        function Carregando(controlDiv, map) 
        {	
            // Css da DIV q contem o controle
            controlDiv.style.padding = '5px';

            // Css da borda do controle e do titulo q sera exibido ao passa o mouse sobre o controle
            var controlUI = document.createElement('DIV');
            controlUI.style.backgroundColor = 'white';
            controlUI.style.borderStyle = 'solid';
            controlUI.style.borderWidth = '2px';
            controlUI.style.cursor = 'pointer';
            controlUI.style.textAlign = 'center';
            controlUI.style.visibility = 'hidden';
            controlUI.title = 'Pesquisando...';
            controlUI.id = 'carregando';
            controlDiv.appendChild(controlUI);

            // CSS para o interior do controle
            var controlText = document.createElement('DIV');
            controlText.style.fontFamily = 'Arial,sans-serif';
            controlText.style.fontSize = '12px';
            controlText.style.paddingLeft = '4px';
            controlText.style.paddingRight = '4px';
            controlText.innerHTML = '<img src="<?php echo $this->baseUrl()?>/public/images/default/carregando.gif" width="16" height="16" />&nbsp;Pesquisando...';
            controlUI.appendChild(controlText);	

        }
        
        /***
         * Controle com o link para criar uma conta
         */
        function criarConta(controlDiv, map) 
        {	
            // Css da DIV q contem o controle
            controlDiv.style.padding = '5px';

            // Css da borda do controle e do titulo q sera exibido ao passa o mouse sobre o controle
            var controlUI = document.createElement('DIV');
            controlUI.style.backgroundColor = 'white';
            controlUI.style.borderStyle = 'solid';
            controlUI.style.borderWidth = '2px';
            controlUI.style.cursor = 'pointer';
            controlUI.style.textAlign = 'center';
            controlUI.title = 'Cadastrar Oferta';
            controlUI.id = 'cadastarOferta';
            controlDiv.appendChild(controlUI);

            // CSS para o interior do controle
            var controlText = document.createElement('DIV');
            controlText.style.fontFamily = 'Arial,sans-serif';
            controlText.style.fontSize = '12px';
            controlText.style.paddingLeft = '4px';
            controlText.style.paddingRight = '4px';
            controlText.innerHTML = '<a href="javascript:;" onclick="cadastrarOferta();">Cadastar Oferta?</a>';
            controlUI.appendChild(controlText);	

        }

        function carregaControles(map)
        {
            // Cria a DIV de controle e chama o controtur raioControle() passando essa DIV
            var raioControleDiv = document.createElement('DIV');
            var raioControle    = new RaioControle(raioControleDiv, map);		
            raioControleDiv.index = 1;
            map.controls[google.maps.ControlPosition.BOTTOM_CENTER].push(raioControleDiv);

            // Cria a DIV de controle para exibir um "Pesquisando..."
            var carregandoDiv   = document.createElement('DIV');
            var carregando      = new Carregando(carregandoDiv, map);		
            carregandoDiv.index = 2;
            map.controls[google.maps.ControlPosition.BOTTOM_CENTER].push(carregandoDiv);
            
            // Cria a DIV de controle para exibir o link "Cadastar Oferta?"
            var cadastarOfertaDiv   = document.createElement('DIV');
            var cadastarOferta      = new criarConta(cadastarOfertaDiv, map);		
            cadastarOfertaDiv.index = 3;
            map.controls[google.maps.ControlPosition.TOP_RIGHT].push(cadastarOfertaDiv);
        }

        /*
        inicializa o mapa e o configura
        */
        function initialize() 
        {

            var mapOptions = {
              center: new google.maps.LatLng(lat, lng),
              zoom: 16,
                      mapTypeControl: true,
                      mapTypeControlOptions: {
                        style: google.maps.MapTypeControlStyle.DROPDOWN_MENU
                      },
              mapTypeId: google.maps.MapTypeId.ROADMAP
                      /*ROADMAP displays the normal, default 2D tiles of Google Maps.
                            SATELLITE displays photographic tiles.
                            HYBRID displays a mix of photographic tiles and a tile layer for prominent features (roads, city names).
                            TERRAIN displays physical relief tiles for displaying elevation and water features (mountains, rivers, etc.).*/
            };

            var map = new google.maps.Map(document.getElementById("map_canvas"),mapOptions);

            //carrega os controles do map
            carregaControles(map);

            // Listener ao clicar colocar o posicao atual e faz a pesquisa nesta area
            google.maps.event.addListener(map, 'click', function(event) {
                                            estouAqui(event.latLng,map);
                                                                      });

            //precionar o mouse, coloca um controle q simplismente informa uma mensagem no mapa, dizendo q esta pesquisando
            google.maps.event.addListener(map,"mousedown", function(event){ 
                                            document.getElementById('carregando').style.visibility='visible';
                                                                     });
            google.maps.event.addListener(map,"mouseup", function(){ 
                                            document.getElementById('carregando').style.visibility='hidden';
                                                                     });
            //marca a posicao atual do usuario, ao inicializar o programa
            center = new google.maps.LatLng(lat, lng);
            estouAqui(center,map);
        }

        /***
        para pegar longitude e latitude do usuer
        */
        function showPosition(position)
        {
            lat = position.coords.latitude;
            lng = position.coords.longitude;

            initialize();
        }

        /***
        Pegar as coordedanas do user, usando geolocation do html5
        */
        function getLocation()
        {

            if (navigator.geolocation)
            {
                navigator.geolocation.getCurrentPosition(showPosition,showError);
            }
            else
            {
                showAlert("Geolocalizaçaoo não é suportado por este navegador. Contudo, você pode usar o programa, basta clicar no mapa aonde deseja pesquisar.");
                initialize();
            }
        }


        function showError(error)
        {
            switch(error.code) 
            {
                case error.PERMISSION_DENIED:
                    erro.innerHTML="Usuário Negado na requisiçãoo para Geolocation."
                    break;
                case error.POSITION_UNAVAILABLE:
                    erro.innerHTML="A localização informada não é validada."
                    break;
                case error.TIMEOUT:
                    erro.innerHTML="O tempo de busca excedeu."
                    break;
                case error.UNKNOWN_ERROR:
                    erro.innerHTML="Um erro desconhecido ocorreu."
                    break;
            }
        }

        //faz um marker, com a localizacao do user
        function estouAqui(position, map) 
        {			
            deleteOverlaysMarkerEstouAqui();

            deleteOverlaysCirculo();

            marker = new google.maps.Marker({
                              position: position,
                              map: map,
                              icon: '<?php echo $this->baseUrl()?>/public/images/default/you-are-here-2.png'
                            });

            //para centralizar
            map.panTo(position);

            //atualiza as variaveis lat e lng com a position do marker
            lat = position.lat();
            lng = position.lng();

            //adicionar no array
            markerEstouAqui.push(marker);

            //ao clicar no marker, um balao sera exibido
            var infowindow = new google.maps.InfoWindow({
                content: 'Você esta aqui!'
            });

            google.maps.event.addListener(markerEstouAqui[0], 'click', function() {
                                            infowindow.open(map,markerEstouAqui[0]);
            });

            var ciruloOptions = {
                    strokeColor: "#0000FF",
                    strokeOpacity: 0.8,
                    strokeWeight: 2,
                    fillColor: "#0000FF",
                    fillOpacity: 0.35,
                    map: map,
                    center: position,
                    radius: raio
            };

            circulo = new google.maps.Circle(ciruloOptions);

            url = urlAjaxMecBusca+'/latitude/'+lat+'/longitude/'+lng+'/raio/'+raio+'/id_categoria/'+id_categoria;
            //inicializa a busca por ofertas
            ajax(url,'tempMap');

            //faz as marcas no mapa
            preparaArraymarkerOferta(map);

            //retira a mensagem de pesquisando do mapa
            document.getElementById('carregando').style.visibility='hidden';

        }

        //deleta o circulo da busca antiga
        function deleteOverlaysCirculo()
        {
            if(circulo)
                circulo.setMap(null);
        }

        // Se o usuario acessa o programa pelo navegador, ele informa a sua localizacao.
        // Porem ele pode escolher pesquisar uma outra localizacao, mas como ele so pode estar em um unico
        // lugar por vez, a antiga marcacao tem q ser deletada.
        // É isso q a deleteOverlaysMarkerEstouAqui() faz
        function deleteOverlaysMarkerEstouAqui() 
        {
            if (markerEstouAqui[0]) 
            {
                markerEstouAqui[0].setMap(null);
            }

            markerEstouAqui.length = 0;		
        }

        //deleta tds os marker's de outra pesquisa
        function deleteOverlaysMarkerOferta() 
        {
            if (markerOferta) 
            {
                for (i in markerOferta) 
                {
                    //retira um marker do mapa
                    markerOferta[i].setMap(null);
                }
                markerOferta.length = 0;
            }
        }

        //verifica se é vazio
        function isEmpty(texto)
        {
            return (texto.length) 
        }

        //monta os arrays, para q cada oferta tenha um marker, com informacoes vindas do BD
        function preparaArraymarkerOferta(map)
        {
            //deleta tds os markerÂ´s de outra pesquisa
            deleteOverlaysMarkerOferta();

            var pontosLg = null;
            var pontosLt = null;
            var html = null;
            var icon = null;
            pontosLg = new Array();
            pontosLt = new Array();
            html = new Array();
            icon = new Array();
            id_oferta = new Array();

            //preenche esta var com os dados retornados pelo BD
            pontosDoBanco = document.getElementById('tempMap').innerHTML;

            //funcao nativa do jsp q transforma um string em codigo
            // com isso, preenche os arrays com os dados da oferta
            eval(pontosDoBanco);

            //se tiver resultado na area pesquisada, monta os markes
            if(isEmpty(document.getElementById('tempMap').innerHTML)>1)
            {
                    //monta o marker de cada orferta
                    for (var i = 0; i < pontosLg.length; i++) 
                    {
                            criarMarcaOferta(map,pontosLt[i], pontosLg[i], html[i],i,icon[i],id_oferta[i]);
                    }
            }
            else
                    showAlert('Não há ofertas na sua localidade');

            //limpa a div q trouxe o resultado da consulta com o banco de dados
            document.getElementById('tempMap').innerHTML = '';
        }

        // cria um marker no mapa
        function criarMarcaOferta(map,lat, lng, html,i, icon,id_oferta)
        {

            marker = new google.maps.Marker({
                      position: new google.maps.LatLng(lat, lng),
                      map: map,
                      openInfoWindowHtml: html,
                      icon: icon
                    });

            //adiciona no array
            markerOferta.push(marker);

            //ao clicar no marker, um balao sera exibido
            var infowindow = new google.maps.InfoWindow({
            content: html
            });			
            google.maps.event.addListener(markerOferta[i], 'click', function() {
                    infowindow.open(map,markerOferta[i]);
                    gravaClick(id_oferta);
            });
        }

        function showAlert(msg)
        {
            <?php if(isset($this->android)){ echo 'showAndroidToast(msg);';}else{ echo "alert(msg)";}?>
        }
        
        function cadastrarOferta(){
            window.location = "<?php echo $this->url(array('module' => 'sistema', 'controller' => 'index', 'action' => 'index'), null, 1); ?>"
        }
    </script>
    <title>PF - Ofertas</title>
    </head>
<body>
    <?php echo $this->Layout()->content; ?>    
</body>
</html>

