
<?php
    /* * *
    * Carrega o menu baseado nas permissoes do usuario
    */
    $arrayIdentity = Zend_Auth::getInstance()->getIdentity();

    $usuario = new Application_Model_Usuario();
    $resultado = $usuario->getPermissao();
?>

<p align="right"><?php echo $arrayIdentity->login; ?> | <a href="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'index', 'action' => 'logout'), null, 1); ?>">sair</a></p>

<?php
    echo '<ul id="nav">'."\n".'
                <li class="current"><a href="/pinho/sistema/logado">Home</a></li>'."\n";
    
    function montaMenu($id_funcionalidade,$resultado)
    {
        foreach ($resultado as $value) 
        {
            
            if ($value['id_funcionalidade_pai']==$id_funcionalidade)
            {
                
                if($value['action']=='')
                {
                    echo "<li><a href='#'>".$value['titulo']."</a>\n";
                        echo  "<ul>\n";
                }
                else
                {
                    echo "<li><a href='#'>".$value['titulo']."</a></li>\n";
                }
                
                //echo $value['titulo']." ".$value['action']."\n";
                
                montaMenu($value['id_funcionalidade'],$resultado);//,$menu);
                
                if($value['action']=='')
                {
                    echo "</ul>\n";
                    echo "</li>\n";
                }
            }
        }
        
    }
    
    //$menu = 
    montaMenu(0,$resultado);
    
    echo '</ul>';
    ?>
    
    
    

