
<?php
    /* * *
    * Carrega o menu baseado nas permissoes do usuario
    */

    $_SESSION['menu'] = null;
    unset($_SESSION['menu']);
    
    $arrayIdentity = Zend_Auth::getInstance()->getIdentity();

    $usuario = new Application_Model_Usuario();
    $resultado = $usuario->getPermissao();
    //print_r($resultado);
?>

<p align="right"><?php echo $arrayIdentity->login; ?> | <a href="<?php echo $this->url(array('module' => 'sistema', 'controller' => 'index', 'action' => 'logout'), null, 1); ?>">sair</a></p>

<?php
    $_SESSION['menu'] = '';
    $_SESSION['menu'] .= '<ul id="nav">'."\n".'
                <li class="current"><a href="/pinho/sistema/logado">Home</a></li>'."\n";
    
    function montaMenu($id_funcionalidade,$resultado,$url)
    {
        foreach ($resultado as $value) 
        {
            
            if ($value['id_funcionalidade_pai']==$id_funcionalidade)
            {
                
                if($value['action']=='')
                {
                    $_SESSION['menu'] .= "<li><a href='#'>".$value['titulo']."</a>\n";
                        $_SESSION['menu'] .=  "<ul>\n";
                }
                else
                {                    
                    $_SESSION['menu'] .= "<li><a href='".$url.$value['action']."'>".$value['titulo']."</a></li>\n";
                }
                
                //echo $value['titulo']." ".$value['action']."\n";
                
                montaMenu($value['id_funcionalidade'],$resultado,$url);//,$menu);
                
                if($value['action']=='')
                {
                    $_SESSION['menu'] .= "</ul>\n";
                    $_SESSION['menu'] .= "</li>\n";
                }
            }
        }
        
    }
    
    montaMenu(0,$resultado,$this->url(array('module' => 'sistema', 'controller' => 'logado', 'action' => ''), null, 1));
    
    $_SESSION['menu'] .= '</ul>';
    
    
    echo $_SESSION['menu'];
    
    $_SESSION['menu'] = null;
    unset($_SESSION['menu']);
 