<?php

/***
 * Carrega o menu baseado nas permissoes do usuario
 */
    $arrayIdentity = Zend_Auth::getInstance()->getIdentity();
    
    $usuario = new Application_Model_Usuario();
    $resultado=$usuario->getPermissao();
    
    echo print_r($resultado);
    $cont = 0;
    $menu =  '<ul>';
    
    while($cont < count($resultado))
    {
        echo $resultado[$cont]['login'];
        
        //if()
        
        $cont++;
    }
    
    $menu .= '</ul>';
    ?>
    
    <p align="right"><?php echo $arrayIdentity->login;?> | <a href="<?php echo $this->url(array('module'=>'sistema', 'controller'=>'index','action'=>'logout'),null,1); ?>">sair</a></p>
    
    <ul>
        <li>marcio
            <ul>
                <li>dias</li>
                <li>raaaa</li>
            </ul>
        </li>
        <li>sobre</li>
    </ul>