<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-CACHE">
        <title>PF - Sistema Administrativo</title>        
        <link href="<?php echo $this->baseUrl()."/public/twitter/css/bootstrap.css"; ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl()."/public/twitter/css/bootstrap.min.css"; ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl()."/public/twitter/css/bootstrap-responsive.css"; ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl()."/public/twitter/css/bootstrap-responsive.min.css"; ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl()."/public/styles/sistema/estilo.css"; ?>" rel="stylesheet" type="text/css" />
        
        <link href="<?php echo $this->baseUrl()."/library/Plugins/jqueryui/css/smoothness/jquery-ui-1.9.1.custom.css"; ?>" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="<?php echo $this->baseUrl()."/library/Plugins/jqueryui/js/jquery-1.8.2.js"; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl()."/library/Plugins/jqueryui/js/jquery-ui-1.9.1.custom.js"; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl()."/library/Plugins/jquery.limit-1.2.source.js"; ?>"></script>
                
        <script type="text/javascript" src="<?php echo $this->baseUrl()."/public/scripts/utilitario.js" ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl()."/public/scripts/sistema/treemenu.js" ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl()."/public/scripts/sistema/calendario.js" ?>"></script>
        
        <script>
        $(function() {
            $( "#tabs" ).tabs();
        });
        </script>
        <!-- COLOCAR O GOOGLE ANALYTICS -->
    </head>

    <body>
        <?php 
            if(isset($_SESSION['erro_redirect']))
            {    
                echo $_SESSION['erro_redirect'];
                $_SESSION['erro_redirect'] = '';
                unset($_SESSION['erro_redirect']);
            }
        ?>
        
        <?php  
            //Caso tenha dado erro, fica na session.
            ZendUtils::receptorMsg();   
        ?>
        
        <div id="araiz" align="center">
            <div id="topo">
                <img src="" alt="Painel de Controle">
             </div>
            
            <div id="conteudo">   
                <?php
                    if (Zend_Auth::getInstance()->hasIdentity())
                    {
                        //Se ja esta logado, não deve ser exibido o formulario para login, logo deve ser redirecionado para /logado
                        //caso tente acessar sistema/index diretamente
                        $controller = $this->controller;

                        if($controller == "index")
                        {
                            ?>
                            <script>
                                window.location.pathname = '<?php echo $this->baseUrl(); ?>/sistema/logado';
                            </script>
                            <?php
                        }

                ?>
                        <div id="menu">          
                            <?php 
                                include("application/modules/sistema/views/layouts/carregamenu.phtml");
                            ?>
                        </div>
                        
                <?php
                    }                        
                ?>
                                                      
                <?php 
                    //imprime o conteudo da action
                    echo $this->layout()->content; 
                ?>
                            
            </div>           
        </div>                 
        
            
    </body>
</html>