<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>PinhoOnline - Sistema Administrativo</title>
        <link href="<?php echo $this->baseUrl()."/public/styles/sistema/estilo.css"; ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl()."/public/twitter/css/bootstrap.css"; ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl()."/public/twitter/css/bootstrap.min.css"; ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl()."/public/twitter/css/bootstrap-responsive.css"; ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl()."/public/twitter/css/bootstrap-responsive.min.css"; ?>" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="<?php echo $this->baseUrl()."/public/scripts/jquery/jquery-1.8.1.js" ?>"></script>
    </head>

    <body>
        <div id="araiz" align="center">
            <div id="topo">
                <img src="<?php echo $this->baseUrl()."/public/images/sistema/logoMarca.png"; ?>" alt="Painel de Controle">
             </div>
            <div id="conteudo">   
                <?php
                    if (Zend_Auth::getInstance()->hasIdentity())
                    {
                        //Se ja esta logado, não deve ser exibido o formulario para login, logo ser redirecionado para /logado
                        //caso tente acessar sistema/index diretamente
                        $controller = $this->controller;

                        if($controller == "index")
                        {
                            ?>
                            <script>
                                window.location.pathname = '/pinho/sistema/logado';
                            </script>
                            <?php
                        }

                ?>
                        <div id="menu">          
                            <?php 
                                include("/application/modules/sistema/views/layouts/carregamenu.phtml");
                            ?>
                        </div>
                        <div>
                            &nbsp;
                        </div>
                <?php
                    }                        
                ?>
            
                <?php echo $this->layout()->content; ?>
        </div>
    </body>
</html>