<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-CACHE">
        <title>PinhoOnline - Sistema Administrativo</title>
        <link href="<?php echo $this->baseUrl()."/public/styles/sistema/estilo.css"; ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl()."/public/twitter/css/bootstrap.css"; ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl()."/public/twitter/css/bootstrap.min.css"; ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl()."/public/twitter/css/bootstrap-responsive.css"; ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl()."/public/twitter/css/bootstrap-responsive.min.css"; ?>" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="<?php echo $this->baseUrl()."/public/scripts/jquery/jquery-1.8.1.js" ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl()."/public/scripts/utilitario.js" ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl()."/public/scripts/sistema/treemenu.js" ?>"></script>
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.9.0/themes/base/jquery-ui.css" />
        <script src="http://code.jquery.com/jquery-1.8.2.js"></script>
        <script src="http://code.jquery.com/ui/1.9.0/jquery-ui.js"></script>
        
        <script>
        $(function() {
            $( "#tabs" ).tabs();
        });
        </script>
        <!-- COLOCAR O GOOGLE ANALYTICS -->
    </head>

    <body>
        <?php 
            if(isset($_SESSION['erro_redirect']))
            {    
                echo $_SESSION['erro_redirect'];
                $_SESSION['erro_redirect'] = '';
                unset($_SESSION['erro_redirect']);
            }
        ?>
        <div id="mensagem" class="mensagem_acerto">
              
            <a id="btnfechardiv" href="#" onclick="FecharDivMsg()">[Fechar]</a>  
        </div>
        <?php           ZendUtils::receptorMsg();   ?>
        
        <div id="araiz" align="center">
            <div id="topo">
                <img src="<?php echo $this->baseUrl()."/public/images/sistema/logoMarca.png"; ?>" alt="Painel de Controle">
             </div>
            <div id="conteudo">   
                <?php
                    if (Zend_Auth::getInstance()->hasIdentity())
                    {
                        //Se ja esta logado, não deve ser exibido o formulario para login, logo deve ser redirecionado para /logado
                        //caso tente acessar sistema/index diretamente
                        $controller = $this->controller;

                        if($controller == "index")
                        {
                            ?>
                            <script>
                                window.location.pathname = '<?php echo $this->baseUrl(); ?>/sistema/logado';
                            </script>
                            <?php
                        }

                ?>
                        <div id="menu">          
                            <?php 
                                include("/application/modules/sistema/views/layouts/carregamenu.phtml");
                            ?>
                        </div>
                        <div>
                            &nbsp;
                        </div>
                <?php
                    }                        
                ?>
                <div id="togglerMenssagem" class="togglerMenssagem">
                    <div id="effectMenssagem" class="ui-widget-content ui-corner-all">
                        <h3 class="ui-widget-header ui-corner-all"><p id="tituloMsg"></p><a id="btnfechardiv" href="javascript:;" onclick="fecharDivMsg(1,0)">[Fechar]</a></h3>
                        <p id="conteudoMsg"></p>
                    </div>
                </div>
                <?php echo $this->layout()->content; ?>
        
            
        </div>
    </body>
</html>